import type { PersonEnglishTranslation } from "./people-en.js";

export const peopleEnglish40Part3: Record<string, PersonEnglishTranslation> = {
  "gregor-mendel": {
    primaryField: "Science",
    secondaryFields: ["Genetics", "Botany", "Meteorology", "Education"],
    summary: "An Augustinian friar and experimental researcher in the Austrian Empire whose pea-hybrid studies established quantitative patterns of inheritance.",
    events: {
      "1822:1": { title: "Born in Hynčice", description: "Born on 20 July in Hynčice, then in Austrian Silesia" },
      "1840:1": { title: "Entered the Philosophical Institute", description: "Studied at the Philosophical Institute in Olomouc" },
      "1843:1": { title: "Joined the Augustinians", description: "Entered the Old Brno abbey and took the religious name Gregor" },
      "1851:1": { title: "Studied at the University of Vienna", description: "Studied physics, mathematics and natural science from 1851 to 1853" },
      "1854:1": { title: "Began the plant-hybrid research period", description: "Taught in Brno and systematically studied plant hybrids from 1854 to 1864" },
      "1865:1": { title: "Presented the pea experiments", description: "Delivered two lectures to the Natural Science Society in Brno" },
      "1866:1": { title: "Published Experiments on Plant Hybrids", description: "The results appeared in the society's proceedings and initially drew little notice" },
      "1868:1": { title: "Elected abbot", description: "Became abbot of the Augustinian abbey in Old Brno" },
      "1884:1": { title: "Died in Brno", description: "Died on 6 January" },
    },
  },
  "florence-nightingale": {
    primaryField: "Medicine",
    secondaryFields: ["Nursing", "Public health", "Statistics", "Hospital administration", "Social reform"],
    summary: "A British nursing reformer, statistical practitioner and public-health advocate whose Crimean War work and later institutional reforms helped establish professional nursing.",
    events: {
      "1820:1": { title: "Born in Florence", description: "Born on 12 May while her parents were in Italy and named after the city" },
      "1837:1": { title: "Resolved to pursue nursing", description: "During the family's Embley period she described receiving a religious calling; the experience is known from her later account" },
      "1850:1": { title: "Visited Kaiserswerth", description: "First closely studied the deaconess institute's nursing practice" },
      "1851:1": { title: "Trained in nursing", description: "Returned to Kaiserswerth for several months of formal training" },
      "1853:1": { title: "Managed a London care institution", description: "Became superintendent of an establishment for ill gentlewomen on Harley Street" },
      "1854:1": { title: "Led nurses to Scutari", description: "Arrived with 38 volunteer nurses at the British military hospital and worked on care and sanitation" },
      "1855:1": { title: "Inspected Crimean hospitals", description: "Visited hospitals near the front and became seriously ill; the point is an approximate Balaklava-area centroid" },
      "1860:1": { title: "Nightingale Training School opened", description: "Established systematic nurse education at St Thomas' Hospital" },
      "1910:1": { title: "Died in London", description: "Died on 13 August; the map uses a city centroid rather than a private residence" },
    },
  },
  "alexander-fleming": {
    primaryField: "Medicine",
    secondaryFields: ["Bacteriology", "Pharmacology", "Antibiotics", "Immunology"],
    summary: "A Scottish physician and bacteriologist who observed the antibacterial action of a mould at St Mary's Hospital in London and named penicillin. Its clinical and industrial development was a multi-person, multi-institution effort.",
    events: {
      "1881:1": { title: "Born near Lochfield", description: "Born on 6 August near Darvel in Ayrshire; the coordinate is an area centroid" },
      "1895:1": { title: "Moved to London", description: "Relocated to London as a teenager to join his brothers and continue his education" },
      "1901:1": { title: "Entered St Mary's medical school", description: "Began his medical education at St Mary's" },
      "1906:1": { title: "Joined the Inoculation Department", description: "Began bacteriological research in Almroth Wright's group" },
      "1915:1": { title: "Worked in a wartime hospital", description: "Investigated wound infection in France; assignments varied, so the point uses the Boulogne area" },
      "1921:1": { title: "Discovered and named lysozyme", description: "Identified a natural bacteriolytic substance in tissues and secretions" },
      "1928:1": { title: "Observed penicillin's antibacterial action", description: "Noticed that bacteria failed to grow around a contaminating Penicillium mould" },
      "1945:1": { title: "Received the Nobel Prize in Physiology or Medicine", description: "Shared the prize with Howard Florey and Ernst Chain" },
      "1955:1": { title: "Died in London", description: "Died on 11 March" },
    },
  },
  "claude-shannon": {
    primaryField: "Science",
    secondaryFields: ["Information theory", "Mathematics", "Electrical engineering", "Cryptography", "Computer science"],
    summary: "An American mathematician and engineer whose switching theory and information theory supplied a common mathematical framework for digital computing, communication, compression and coding.",
    events: {
      "1916:1": { title: "Born in Petoskey", description: "Born on 30 April and raised in Gaylord, Michigan" },
      "1932:1": { title: "Entered the University of Michigan", description: "Studied mathematics and electrical engineering; the year is the start of the four-year program" },
      "1936:1": { title: "Began research at MIT", description: "Worked with Vannevar Bush's differential analyzer and studied relay circuits" },
      "1938:1": { title: "Completed the switching-circuit thesis", description: "Used Boolean algebra to establish foundations for digital switching theory" },
      "1940:1": { title: "Joined the Institute for Advanced Study", description: "Became a research fellow in Princeton after earning two MIT degrees" },
      "1941:1": { title: "Joined Bell Laboratories", description: "Worked on communication, cryptography and wartime control systems" },
      "1948:1": { title: "Published the foundational information-theory paper", description: "A Mathematical Theory of Communication appeared in the Bell System Technical Journal" },
      "1956:1": { title: "Returned to MIT", description: "Joined as a visiting professor, later became Donner Professor and retired in 1978" },
      "2001:1": { title: "Died in Medford", description: "Died on 24 February" },
    },
  },
  "cai-lun": {
    primaryField: "Industry and technology",
    secondaryFields: ["Papermaking", "Materials technology", "Court administration"],
    summary: "An Eastern Han court official traditionally credited with improving the materials and process of an existing papermaking tradition and reporting it to the court in 105. His birth is variously dated to 61 or 63, and most details come from later histories.",
    events: {
      "61:1": { title: "Traditionally born in Guiyang Commandery", description: "Common dates are 61 or 63; the point uses modern Leiyang, while the ancient commandery was much larger" },
      "75:1": { title: "Entered the Luoyang court, approximately", description: "The Book of the Later Han says at the end of Yongping; 75 is only a visualization anchor" },
      "89:1": { title: "Appointed Director of the Imperial Workshops", description: "Oversaw production of court objects after Emperor He's accession; the year follows the common chronology" },
      "97:1": { title: "Worked on court texts", description: "Traditional chronology associates him with textual collation at the Eastern Library; details come from later histories" },
      "105:1": { title: "Reported an improved papermaking method", description: "Later Han history says he used bark, hemp waste, rags and old fishing nets and presented the method to the court" },
      "114:1": { title: "Enfeoffed as Marquis of Longting", description: "The fief is usually associated with modern Hanzhong; its exact ancient boundary is uncertain" },
      "121:1": { title: "Died amid a court purge", description: "The account that he took poison before imprisonment derives from the later Book of the Later Han" },
    },
  },
  "ada-lovelace": {
    primaryField: "Industry and technology",
    secondaryFields: ["Mathematics", "Computing", "Writing"],
    summary: "A British mathematical writer whose extensive notes on the Analytical Engine described broader symbolic uses and included a method for calculating Bernoulli numbers. The label first programmer depends on contested definitions.",
    events: {
      "1815:1": { title: "Born in London", description: "Born on 10 December as Augusta Ada Byron" },
      "1828:1": { title: "Developed a Flyology project", description: "As a teenager studied bird wings and imagined a flying apparatus; no practical aircraft resulted" },
      "1833:1": { title: "Met Charles Babbage", description: "Saw a Difference Engine demonstration at a London gathering and began a long correspondence" },
      "1835:1": { title: "Married William King", description: "The marriage is associated with Ockham; she became Countess of Lovelace in 1838" },
      "1840:1": { title: "Studied advanced mathematics with De Morgan", description: "Received guidance by correspondence; the point uses the center of their London scholarly network" },
      "1842:1": { title: "Translated the Analytical Engine paper", description: "Began translating Luigi Menabrea's French account of Babbage's Analytical Engine" },
      "1843:1": { title: "Published the Analytical Engine notes", description: "The translation appeared with Notes A–G, including a Bernoulli-number table" },
      "1852:1": { title: "Died in London", description: "Died on 27 November" },
    },
  },
  "thomas-edison": {
    primaryField: "Industry and technology",
    secondaryFields: ["Electrical engineering", "Sound recording", "Motion pictures", "Industrial research", "Business"],
    summary: "An American inventor and entrepreneur who organized team-based research at Menlo Park and West Orange and advanced sound recording, electric-light systems, power distribution and early film. Many achievements were collaborative developments rather than isolated solo inventions.",
    events: {
      "1847:1": { title: "Born in Milan, Ohio", description: "Born on 11 February" },
      "1854:1": { title: "Moved to Port Huron", description: "Relocated with his family and spent his youth in Michigan" },
      "1859:1": { title: "Worked on the railroad", description: "Around age twelve sold newspapers on the Grand Trunk Railway and pursued experiments" },
      "1862:1": { title: "Became a telegraph operator", description: "Learned telegraphy and then worked in several U.S. cities" },
      "1870:1": { title: "Established a Newark laboratory", description: "Proceeds from an improved stock ticker helped him organize a development shop" },
      "1876:1": { title: "Established the Menlo Park laboratory", description: "Created a team-based research site with machine shops and continuous experimentation" },
      "1877:1": { title: "Demonstrated the phonograph", description: "Developed a machine capable of recording and reproducing sound" },
      "1879:1": { title: "Improved a practical incandescent-light system", description: "The team achieved a longer-lasting lamp design; it was not the first electric lamp in history" },
      "1882:1": { title: "Pearl Street Station began service", description: "An integrated direct-current lighting and power system supplied part of Manhattan" },
      "1887:1": { title: "Opened the West Orange laboratory", description: "Expanded research, manufacturing experiments and technical collections on a larger scale" },
      "1931:1": { title: "Died in West Orange", description: "Died on 18 October" },
    },
  },
  "tim-berners-lee": {
    primaryField: "Industry and technology",
    secondaryFields: ["Computer science", "Web standards", "Open technology", "Data governance"],
    summary: "A British computer scientist who proposed and implemented the core components of the World Wide Web at CERN and later founded W3C to coordinate URI, HTTP, HTML and open standards. He is living, and the route uses only public city and institutional locations.",
    events: {
      "1955:1": { title: "Born in London", description: "Born on 8 June; only a city centroid is used, with no private location recorded" },
      "1976:1": { title: "Graduated from Oxford", description: "Studied physics at Queen's College and received his degree" },
      "1980:1": { title: "First worked at CERN", description: "As an independent contractor, developed ENQUIRE to organize information through hypertext relationships" },
      "1984:1": { title: "Returned to CERN", description: "Rejoined as a fellow and worked on distributed scientific information" },
      "1989:1": { title: "Proposed the World Wide Web", description: "Submitted a proposal for an Internet-based hypertext information system" },
      "1990:1": { title: "Built the first Web client and server", description: "Implemented key forms of HTML, HTTP and URL and created the first website" },
      "1993:1": { title: "CERN released the Web software openly", description: "On 30 April CERN placed core software in the public domain; this was an institutional decision" },
      "1994:1": { title: "Founded W3C at MIT", description: "Organized cross-institutional collaboration on open Web standards" },
      "2016:1": { title: "Joined Oxford's Department of Computer Science", description: "Continued public institutional work on decentralized Web and sociotechnical questions" },
    },
  },
  "zheng-he": {
    primaryField: "Navigation and exploration",
    secondaryFields: ["Diplomacy", "Military affairs", "Maritime trade", "Imperial administration"],
    summary: "A Ming eunuch, commander and fleet leader whose seven voyages from 1405 to 1433 projected Ming diplomacy and military power across Southeast Asia, South Asia, the Persian Gulf and East Africa. His birth details and place of death remain disputed.",
    events: {
      "1371:1": { title: "Traditionally born in Kunyang", description: "Born into a Muslim Ma family in Yunnan; 1371 is conventional and details rely largely on later sources" },
      "1382:1": { title: "Captured after the Ming conquest of Yunnan", description: "Taken into the Ming court system while young; precise date and location remain uncertain" },
      "1390:1": { title: "Served in the Prince of Yan's household", description: "Associated with Zhu Di in Beiping; the year is a conservative visualization anchor" },
      "1405:1": { title: "Departed on the first voyage", description: "The fleet left through the Nanjing–Taicang maritime system; assembly and sea departure involved several sites" },
      "1407:1": { title: "Defeated Chen Zuyi's forces at Palembang", description: "Used force against a local maritime power on the return route; the voyages were not purely peaceful visits" },
      "1411:1": { title: "Intervened in a Ceylon conflict", description: "The fleet fought a local ruler; the exact battlefield is unknown" },
      "1415:1": { title: "Reached Hormuz on the fourth voyage", description: "The fleet's route clearly extended to the major Persian Gulf port" },
      "1419:1": { title: "The fifth voyage connected with East African ports", description: "Missions reached Malindi and other ports; Zheng He's personal presence on every detached squadron cannot be confirmed" },
      "1431:1": { title: "Commissioned to lead the seventh voyage", description: "Led the final expedition after a long pause; the fleet's departure process continued into 1432" },
      "1433:1": { title: "Died around the final voyage", description: "Accounts place his death at Calicut, at sea on the return, or after returning to China; the point is only a disputed-location anchor" },
    },
  },
  "william-shakespeare": {
    primaryField: "Art",
    secondaryFields: ["Drama", "Poetry", "Acting", "Theatre business"],
    summary: "An English playwright, poet, actor and company shareholder whose language, characterization and dramatic structures have had enduring global influence. Birth on 23 April is a traditional inference from the documented baptism.",
    events: {
      "1564:1": { title: "Born and baptized in Stratford", description: "His baptism on 26 April is documented; birth on 23 April is a traditional inference" },
      "1582:1": { title: "Married Anne Hathaway", description: "A license and bond survive, but the exact church of the ceremony remains disputed" },
      "1585:1": { title: "Twins baptized", description: "The baptism of Hamnet and Judith is a key documented point before the lost years" },
      "1592:1": { title: "Documented in the London theatre world", description: "The first definite surviving reference identifies him as an established actor and playwright" },
      "1593:1": { title: "Published Venus and Adonis", description: "His first securely documented printed work appeared in London" },
      "1594:1": { title: "Joined the Lord Chamberlain's Men", description: "Worked as actor, writer and shareholder; the company became the King's Men in 1603" },
      "1599:1": { title: "The Globe Theatre was built", description: "The company reused timbers from an older theatre, and Shakespeare held a share" },
      "1603:1": { title: "The company became the King's Men", description: "Royal patronage under James I strengthened the company's position" },
      "1613:1": { title: "The Globe burned", description: "A fire during Henry VIII destroyed the theatre; his late life was increasingly centered on Stratford" },
      "1616:1": { title: "Made his will and died", description: "Signed his will in March, died on 23 April and was buried at Holy Trinity Church" },
    },
  },
  "martin-luther-king-jr": {
    primaryField: "Politics",
    secondaryFields: ["Civil rights", "Religion", "Nonviolent movements", "Social justice"],
    summary: "An American Baptist minister and civil-rights leader who used mass organizing, litigation, boycotts and nonviolent direct action to advance desegregation and voting rights. The achievements belonged to a broad movement, not one individual alone.",
    events: {
      "1929:1": { title: "Born in Atlanta", description: "Born on 15 January; early records use Michael King Jr., and he was later renamed with his father" },
      "1948:1": { title: "Entered Crozer Theological Seminary", description: "Pursued theological study and graduated in 1951" },
      "1951:1": { title: "Began doctoral study at Boston University", description: "Studied systematic theology and met Coretta Scott in Boston" },
      "1954:1": { title: "Became pastor of Dexter Avenue Baptist Church", description: "Moved to Montgomery and built a base in church and community work" },
      "1955:1": { title: "Helped lead the Montgomery bus boycott", description: "Became a prominent spokesperson and organizer after Rosa Parks's arrest" },
      "1957:1": { title: "Helped found the Southern Christian Leadership Conference", description: "Coordinated nonviolent civil-rights action through Southern church networks" },
      "1959:1": { title: "Visited India to study Gandhian nonviolence", description: "Led a delegation visiting several cities; New Delhi is used as the public anchor" },
      "1963:1": { title: "Participated in the Birmingham campaign", description: "Demonstrations, imprisonment and his public letter focused national attention on segregation" },
      "1963:2": { title: "Spoke at the March on Washington", description: "Delivered the I Have a Dream address at the Lincoln Memorial; the march was jointly led by many organizations" },
      "1964:1": { title: "Received the Nobel Peace Prize", description: "Accepted the award in Oslo on behalf of the civil-rights movement" },
      "1965:1": { title: "Advanced the Selma voting-rights campaign", description: "Joined the successful march to Montgomery; the coordinate uses the Selma starting point" },
      "1968:1": { title: "Assassinated in Memphis", description: "Killed on 4 April while supporting striking sanitation workers" },
    },
  },
  "nelson-mandela": {
    primaryField: "Politics",
    secondaryFields: ["Anti-apartheid struggle", "Law", "Statecraft", "Reconciliation", "Human rights"],
    summary: "A South African anti-apartheid leader, political prisoner and the country's first Black president elected by universal suffrage, central to the negotiated transition from white-minority rule to multiracial democracy. The movement's collective nature remains essential.",
    events: {
      "1918:1": { title: "Born in Mvezo", description: "Born on 18 July in Mvezo, Transkei" },
      "1939:1": { title: "Entered University College of Fort Hare", description: "Began higher education and left in 1940 amid a student protest dispute" },
      "1941:1": { title: "Arrived in Johannesburg", description: "After fleeing an arranged marriage, entered the city's work, legal and political networks" },
      "1944:1": { title: "Co-founded the ANC Youth League", description: "Worked with Walter Sisulu, Oliver Tambo and others to advance more assertive mass politics" },
      "1952:1": { title: "Led the Defiance Campaign and opened a law practice", description: "Helped organize civil disobedience and founded a law firm with Tambo" },
      "1955:1": { title: "Witnessed adoption of the Freedom Charter", description: "Followed the Congress of the People under restrictions imposed by banning orders" },
      "1962:1": { title: "Arrested near Howick", description: "Captured after underground activity and travel in Africa; the point uses the public capture-site memorial area" },
      "1964:1": { title: "Sentenced to life and imprisoned on Robben Island", description: "Began long imprisonment after the Rivonia Trial; he was later transferred elsewhere" },
      "1990:1": { title: "Released from prison", description: "Walked free from Victor Verster Prison on 11 February and entered open negotiations" },
      "1993:1": { title: "Shared the Nobel Peace Prize", description: "Honored with F. W. de Klerk for ending apartheid and laying foundations for democratic transition" },
      "1994:1": { title: "Inaugurated as president of South Africa", description: "Formed a new government after the first national nonracial election" },
      "2013:1": { title: "Died in Johannesburg", description: "Died on 5 December; the map uses only a city centroid" },
    },
  },
  "rachel-carson": {
    primaryField: "Science",
    secondaryFields: ["Marine biology", "Conservation", "Science writing", "Public policy"],
    summary: "An American marine biologist and science writer whose books on the sea and Silent Spring brought ecological evidence into public debate and pesticide-policy review. Later reforms were collective outcomes involving scientists, civil society and government.",
    events: {
      "1907:1": { title: "Born in Springdale", description: "Born on 27 May in the Allegheny River region of Pennsylvania" },
      "1925:1": { title: "Entered Pennsylvania College for Women", description: "Began in English and later changed her major to biology" },
      "1929:1": { title: "Studied at the Marine Biological Laboratory", description: "Gained intensive experience with marine research and continued in biology" },
      "1929:2": { title: "Entered Johns Hopkins University", description: "Pursued graduate zoology despite financial constraints" },
      "1935:1": { title: "Wrote radio programs for the Bureau of Fisheries", description: "Produced a marine-life series in a part-time federal role" },
      "1936:1": { title: "Appointed junior aquatic biologist", description: "Became one of the bureau's few women professionals and conducted Chesapeake Bay fieldwork" },
      "1941:1": { title: "Published Under the Sea-Wind", description: "Presented marine ecology to the public through literary narrative; the point uses her federal work city" },
      "1951:1": { title: "Published The Sea Around Us", description: "Its success enabled her to leave government and write full-time; the point uses the public city centroid" },
      "1962:1": { title: "Published Silent Spring", description: "Issued by Houghton Mifflin in Boston, prompting national debate over pesticide risks" },
      "1963:1": { title: "Testified to Congress on pesticides", description: "Supported federal review and argued for cautious, scientifically governed chemical use" },
      "1964:1": { title: "Died", description: "Died of cancer on 14 April; no private residence is mapped" },
    },
  },
};
