export type PersonEnglishTranslation = {
  primaryField: string;
  secondaryFields: string[];
  summary: string;
  events: Record<string, { title: string; description: string }>;
};

export const newEnglishPeople: Record<string, PersonEnglishTranslation> = {
  confucius: {
    primaryField: "Thought and education",
    secondaryFields: ["Philosophy", "Ethics", "Political thought", "Education"],
    summary: "An ancient Chinese thinker and educator whose ideas on ethics, ritual and government became foundational across East Asia. His dates and parts of his itinerary follow a traditional, uncertain chronology.",
    events: {
      "-551:1": { title: "Traditionally born in Zou, in the state of Lu", description: "Traditional birth date; the map uses the Qufu area" },
      "-509:1": { title: "Associated with office and ritual affairs in Lu", description: "Approximate traditional biographical anchor" },
      "-501:1": { title: "Traditionally appointed governor of Zhongdu", description: "Traditional appointment" },
      "-497:1": { title: "Traditionally left Lu for Wei", description: "Traditional itinerary" },
      "-492:1": { title: "Traditionally travelled through Song", description: "Traditional itinerary" },
      "-489:1": { title: "Traditionally stranded between Chen and Cai", description: "Traditional itinerary; date uncertain" },
      "-484:1": { title: "Traditionally returned to Lu", description: "Teaching and textual work" },
      "-479:1": { title: "Traditionally died in Lu", description: "Traditional death date" },
    },
  },
  "siddhartha-gautama": {
    primaryField: "Religion",
    secondaryFields: ["Philosophy", "Ethics", "Monastic institutions", "Education"],
    summary: "Founder of the Buddhist tradition, whose teachings on suffering, practice and liberation shaped a major Asian and global religious-philosophical tradition. The timeline uses the disputed traditional long chronology only as display anchors.",
    events: {
      "-563:1": { title: "Traditionally born at Lumbini", description: "Traditional birth date; the year is disputed" },
      "-534:1": { title: "Traditionally left Kapilavastu to seek liberation", description: "Traditional place and date anchor" },
      "-528:1": { title: "Traditionally practised near Rajgir", description: "Traditional place of practice" },
      "-528:2": { title: "Traditionally attained awakening at Bodh Gaya", description: "Traditional place of awakening" },
      "-528:3": { title: "Traditionally gave the first teaching at Sarnath", description: "Traditional teaching place" },
      "-500:1": { title: "Traditionally taught at Shravasti", description: "Representative mid-life anchor, not a precise year" },
      "-483:1": { title: "Traditional last journey through Vaishali", description: "Traditional itinerary" },
      "-483:2": { title: "Traditionally died at Kushinagar", description: "Traditional place and date of death" },
    },
  },
  aristotle: {
    primaryField: "Thought and education",
    secondaryFields: ["Philosophy", "Logic", "Biology", "Ethics", "Political thought"],
    summary: "A Greek philosopher whose work in logic, nature, ethics and politics shaped European and Islamic intellectual traditions for more than two millennia.",
    events: {
      "-384:1": { title: "Born in Stagira", description: "Birth" },
      "-367:1": { title: "Entered Plato's Academy in Athens", description: "Education" },
      "-347:1": { title: "Left Athens for Assos", description: "Research and teaching" },
      "-345:1": { title: "Conducted biological research on Lesbos", description: "Research" },
      "-343:1": { title: "Tutored the young Alexander at Pella", description: "Education" },
      "-335:1": { title: "Founded the Lyceum in Athens", description: "Education and research" },
      "-323:1": { title: "Left Athens for Chalcis", description: "Relocation" },
      "-322:1": { title: "Died in Chalcis", description: "Death" },
    },
  },
  "alexander-the-great": {
    primaryField: "Politics",
    secondaryFields: ["Military", "Imperial administration", "State-building", "Hellenistic exchange"],
    summary: "The Macedonian king whose conquests ended the Achaemenid Empire and helped create a Hellenistic world spanning the eastern Mediterranean, Egypt and western Asia.",
    events: {
      "-356:1": { title: "Born in Pella", description: "Birth" },
      "-336:1": { title: "Succeeded to the throne at Aigai", description: "Accession" },
      "-334:1": { title: "Won near the Granicus River", description: "Military; battlefield is approximate" },
      "-331:1": { title: "Founded Alexandria in Egypt", description: "Urban and imperial development" },
      "-331:2": { title: "Defeated Darius III at Gaugamela", description: "Military; battlefield location is debated" },
      "-330:1": { title: "Occupied Persepolis", description: "Military and empire" },
      "-326:1": { title: "Fought in the Hydaspes region", description: "Military; battlefield is approximate" },
      "-323:1": { title: "Died in Babylon", description: "Death" },
    },
  },
  "jesus-of-nazareth": {
    primaryField: "Religion",
    secondaryFields: ["Ethics", "Education", "Social thought"],
    summary: "A first-century Jewish teacher and the central figure of Christianity, whose teachings and later interpretation profoundly shaped global religion, ethics, art and politics. Dates and some locations are approximate and disputed.",
    events: {
      "-5:1": { title: "Traditionally born in Bethlehem", description: "Midpoint anchor for circa 6–4 BCE; location disputed" },
      "-4:1": { title: "Raised in Nazareth", description: "Early-life location; year is a display anchor" },
      "28:1": { title: "Baptised near the Jordan River", description: "Approximate traditional location; candidate sites are disputed" },
      "29:1": { title: "Taught in Galilee", description: "Capernaum is a traditional centre; year approximate" },
      "30:1": { title: "Crucified in Jerusalem", description: "Circa 30 or 33 CE; exact date disputed" },
    },
  },
  muhammad: {
    primaryField: "Religion",
    secondaryFields: ["Politics", "Law", "Community-building", "Military"],
    summary: "The prophet of Islam and leader of the early Muslim community, whose religious teaching and political practice established core foundations of Islamic civilization. Detailed early chronology relies mainly on later traditions.",
    events: {
      "570:1": { title: "Traditionally born in Mecca", description: "Traditional approximate birth date" },
      "610:1": { title: "Traditionally received the first revelation at Jabal al-Nour", description: "Traditional religious event" },
      "622:1": { title: "Migrated to Medina", description: "Migration and community-building" },
      "624:1": { title: "Battle of Badr", description: "Military" },
      "625:1": { title: "Battle of Uhud", description: "Military" },
      "628:1": { title: "Concluded the agreement at Hudaybiyyah", description: "Politics; ancient site boundaries uncertain" },
      "630:1": { title: "Entered Mecca", description: "Politics and religion" },
      "632:1": { title: "Died in Medina", description: "Death" },
    },
  },
  avicenna: {
    primaryField: "Medicine",
    secondaryFields: ["Philosophy", "Logic", "Natural science", "Political administration"],
    summary: "A Persian physician and philosopher whose Canon of Medicine and philosophical system connected Greek, Islamic and Latin European traditions of knowledge. The conventional 980 birth year may be slightly late.",
    events: {
      "980:1": { title: "Traditionally born at Afshana near Bukhara", description: "Birth date may be earlier; modern approximate location" },
      "990:1": { title: "Raised and educated in Bukhara", description: "Early-life display anchor" },
      "999:1": { title: "Moved toward Khwarazm", description: "Relocation, approximately 999–1012" },
      "1012:1": { title: "Stayed near Gorgan", description: "Relocation and medicine" },
      "1014:1": { title: "Practised and served at Rayy", description: "Medicine and appointment" },
      "1015:1": { title: "Served as physician and vizier in Hamadan", description: "Medicine and political administration" },
      "1024:1": { title: "Moved to Isfahan", description: "Research and writing" },
      "1037:1": { title: "Died in Hamadan", description: "Death" },
    },
  },
  "genghis-khan": {
    primaryField: "Politics",
    secondaryFields: ["Military", "State-building", "Imperial administration", "Trade networks", "Law"],
    summary: "Founder of the Mongol Empire, whose conquests and institutional integration reordered Eurasia while causing immense warfare, destruction and loss of life. His birth year and exact birthplace are disputed.",
    events: {
      "1162:1": { title: "Traditionally born in the Onon River region", description: "Mongolian official date; year and location disputed" },
      "1206:1": { title: "Proclaimed Genghis Khan at a kurultai", description: "State-building; meeting site is a regional approximation" },
      "1209:1": { title: "Western Xia submitted", description: "Military and politics" },
      "1215:1": { title: "Mongol forces captured Zhongdu", description: "Military" },
      "1219:1": { title: "Siege of Otrar", description: "Khwarazmian campaign" },
      "1220:1": { title: "Captured Samarkand", description: "Military" },
      "1221:1": { title: "Campaign in the Bamiyan region", description: "Military; details rely on later chronicles" },
      "1227:1": { title: "Died during the Western Xia campaign", description: "Exact place and cause of death unknown" },
    },
  },
  "johannes-gutenberg": {
    primaryField: "Industry and technology",
    secondaryFields: ["Printing", "Engineering", "Publishing", "Knowledge transmission"],
    summary: "A German craftsman and printing innovator who integrated reusable metal type, ink and presswork into a scalable European printing system. His birth is conventionally dated to about 1400.",
    events: {
      "1400:1": { title: "Probably born in Mainz", description: "Inferred birthplace and approximate year" },
      "1434:1": { title: "First documented in Strasbourg", description: "Residence" },
      "1438:1": { title: "Joined a technical and commercial project in Strasbourg", description: "Engineering and business" },
      "1448:1": { title: "Returned to Mainz to establish a venture", description: "Relocation and enterprise" },
      "1450:1": { title: "Developed a printing workshop with Johann Fust", description: "Printing and enterprise" },
      "1455:1": { title: "Completed the 42-line Gutenberg Bible", description: "Printing and publishing; approximate date" },
      "1468:1": { title: "Died in Mainz", description: "Death" },
    },
  },
  "christopher-columbus": {
    primaryField: "Navigation and exploration",
    secondaryFields: ["Navigation", "Colonial expansion", "Atlantic exchange", "Colonial government"],
    summary: "A Genoese mariner whose Castilian-backed voyages initiated sustained European-American contact and also colonial conquest, forced labor, disease transmission and catastrophic Indigenous population loss.",
    events: {
      "1451:1": { title: "Born in Genoa", description: "Birth; exact date lies between August and October" },
      "1492:1": { title: "Sailed from Palos", description: "Navigation" },
      "1492:2": { title: "Landed in the Bahamas", description: "Navigation; the island's identity is disputed" },
      "1492:3": { title: "Reached northeastern Cuba", description: "Navigation; landing place reconstructed" },
      "1492:4": { title: "Established a settlement on Hispaniola", description: "Colonial expansion; exact site uncertain" },
      "1498:1": { title: "Reached the South American coast", description: "Third voyage" },
      "1500:1": { title: "Arrested amid disputes over colonial rule", description: "Colonial government" },
      "1506:1": { title: "Died in Valladolid", description: "Death" },
    },
  },
  "leonardo-da-vinci": {
    primaryField: "Art",
    secondaryFields: ["Engineering", "Anatomy", "Natural science", "Architecture"],
    summary: "A Renaissance artist, engineer and investigator who joined observation, drawing and mechanical design in a single exploratory practice.",
    events: {
      "1452:1": { title: "Born near Vinci", description: "Birth" },
      "1469:1": { title: "Entered Verrocchio's workshop", description: "Artistic education; approximate date" },
      "1482:1": { title: "Entered court service in Milan", description: "Art and engineering; approximate date" },
      "1500:1": { title: "Returned to Florence", description: "Art, engineering and anatomical research" },
      "1513:1": { title: "Moved to Rome to work", description: "Art and engineering" },
      "1516:1": { title: "Moved to Amboise by royal invitation", description: "Relocation and creative work" },
      "1519:1": { title: "Died in Amboise", description: "Death" },
    },
  },
  "martin-luther": {
    primaryField: "Religion",
    secondaryFields: ["Theology", "Social reform", "Translation", "Education"],
    summary: "A German theologian and reformer whose polemics, translation and organizing helped transform European religious and political life.",
    events: {
      "1483:1": { title: "Born in Eisleben", description: "Birth" },
      "1501:1": { title: "Entered the University of Erfurt", description: "Education" },
      "1505:1": { title: "Entered the Augustinian monastery", description: "Religion and education" },
      "1512:1": { title: "Received his doctorate and taught at Wittenberg", description: "Education and religion" },
      "1517:1": { title: "Published the Ninety-five Theses", description: "Reformation; the church-door account is disputed" },
      "1521:1": { title: "Appeared before the Diet of Worms", description: "Religion and politics" },
      "1521:2": { title: "Lived at Wartburg and translated the New Testament", description: "Translation and Reformation" },
      "1522:1": { title: "Returned to Wittenberg", description: "Reformation" },
      "1546:1": { title: "Died in Eisleben", description: "Death" },
    },
  },
  "galileo-galilei": {
    primaryField: "Science",
    secondaryFields: ["Astronomy", "Physics", "Engineering", "Mathematics"],
    summary: "An Italian natural philosopher whose instrumental observations, experiments and mathematical arguments advanced modern astronomy and mechanics.",
    events: {
      "1564:1": { title: "Born in Pisa", description: "Birth" },
      "1581:1": { title: "Entered the University of Pisa", description: "Education" },
      "1589:1": { title: "Appointed professor of mathematics at Pisa", description: "Appointment" },
      "1592:1": { title: "Became professor of mathematics at Padua", description: "Appointment" },
      "1609:1": { title: "Improved the telescope and began systematic observations", description: "Science and engineering" },
      "1610:1": { title: "Returned to Tuscany for a court appointment", description: "Appointment and research" },
      "1611:1": { title: "Presented observations in Rome", description: "Scientific exchange" },
      "1633:1": { title: "Tried by the Roman Inquisition", description: "Trial" },
      "1633:2": { title: "Confined under house arrest at Arcetri", description: "House arrest and research" },
      "1642:1": { title: "Died at Arcetri", description: "Death" },
    },
  },
  "james-watt": {
    primaryField: "Industry and technology",
    secondaryFields: ["Mechanical engineering", "Steam power", "Manufacturing", "Chemistry"],
    summary: "A Scottish engineer whose improvements, including the separate condenser, greatly increased steam-engine efficiency and enabled industrial deployment with Matthew Boulton.",
    events: {
      "1736:1": { title: "Born in Greenock", description: "Birth" },
      "1755:1": { title: "Went to London to learn instrument making", description: "Education" },
      "1757:1": { title: "Established an instrument workshop at Glasgow University", description: "Engineering and enterprise" },
      "1763:1": { title: "Repaired a Newcomen engine model", description: "Engineering research" },
      "1769:1": { title: "Patented the separate condenser", description: "Invention and patent" },
      "1774:1": { title: "Moved to Birmingham to work with Boulton", description: "Relocation and industry" },
      "1777:1": { title: "A Watt engine entered service at Boulton's works", description: "Industrial application" },
      "1819:1": { title: "Died near Birmingham", description: "Death" },
    },
  },
  "adam-smith": {
    primaryField: "Economic and social thought",
    secondaryFields: ["Moral philosophy", "Political economy", "Education", "Public administration"],
    summary: "A Scottish moral philosopher and political economist whose works examined commercial society, division of labor, moral judgment and institutions. His exact birthday is unknown.",
    events: {
      "1723:1": { title: "Born and baptised in Kirkcaldy", description: "Birth year; exact birthday unknown" },
      "1737:1": { title: "Entered the University of Glasgow", description: "Education" },
      "1740:1": { title: "Went to Oxford to study", description: "Education" },
      "1748:1": { title: "Began public lectures in Edinburgh", description: "Education" },
      "1751:1": { title: "Appointed professor at Glasgow", description: "Appointment and education" },
      "1764:1": { title: "Stayed in Toulouse", description: "Travel and research" },
      "1766:1": { title: "Met Enlightenment thinkers in Paris", description: "Intellectual exchange" },
      "1767:1": { title: "Returned to Kirkcaldy to write The Wealth of Nations", description: "Writing" },
      "1778:1": { title: "Appointed Commissioner of Customs for Scotland", description: "Public administration" },
      "1790:1": { title: "Died in Edinburgh", description: "Death" },
    },
  },
  "charles-darwin": {
    primaryField: "Science",
    secondaryFields: ["Biology", "Geology", "Natural history", "Science writing"],
    summary: "A British naturalist who explained evolution by natural selection and built evidence through global travel, specimens and correspondence.",
    events: {
      "1809:1": { title: "Born in Shrewsbury", description: "Birth" },
      "1825:1": { title: "Entered the University of Edinburgh to study medicine", description: "Education" },
      "1828:1": { title: "Entered Christ's College, Cambridge", description: "Education" },
      "1831:1": { title: "Boarded HMS Beagle at Plymouth", description: "Voyage and research" },
      "1832:1": { title: "Observed tropical nature in Bahia, Brazil", description: "Scientific fieldwork" },
      "1835:1": { title: "Studied the Galápagos Islands", description: "Scientific fieldwork; archipelago centroid" },
      "1836:1": { title: "Completed the Beagle voyage", description: "Return to England" },
      "1837:1": { title: "Organised voyage materials in London", description: "Research" },
      "1842:1": { title: "Moved to Down", description: "Residence and research" },
      "1858:1": { title: "Natural-selection papers read at the Linnean Society", description: "Publication; Darwin did not attend" },
      "1859:1": { title: "On the Origin of Species was published", description: "Publication location anchor, not a move" },
      "1882:1": { title: "Died at Down", description: "Death" },
    },
  },
  "karl-marx": {
    primaryField: "Economic and social thought",
    secondaryFields: ["Philosophy", "Politics", "Journalism", "Social movements"],
    summary: "A German philosopher, critic of political economy and revolutionary socialist whose writings and organizing profoundly influenced modern political movements and states.",
    events: {
      "1818:1": { title: "Born in Trier", description: "Birth" },
      "1835:1": { title: "Entered the University of Bonn to study law", description: "Education" },
      "1836:1": { title: "Transferred to the University of Berlin", description: "Education" },
      "1842:1": { title: "Edited the Rheinische Zeitung in Cologne", description: "Journalism" },
      "1843:1": { title: "Moved to Paris", description: "Relocation and research" },
      "1845:1": { title: "Expelled and moved to Brussels", description: "Exile and organizing" },
      "1848:1": { title: "Returned to Cologne and founded the Neue Rheinische Zeitung", description: "Journalism and politics" },
      "1849:1": { title: "Arrived in London and settled there", description: "Exile and research" },
      "1864:1": { title: "Helped found the International Workingmen's Association", description: "Organizing" },
      "1867:1": { title: "Volume I of Capital was published", description: "Writing and publication" },
      "1883:1": { title: "Died in London", description: "Death" },
    },
  },
  "marie-curie": {
    primaryField: "Science",
    secondaryFields: ["Physics", "Chemistry", "Medical technology", "Education"],
    summary: "A Polish-born French physicist and chemist who pioneered radioactivity research and helped apply it to medicine.",
    events: {
      "1867:1": { title: "Born in Warsaw", description: "Birth" },
      "1891:1": { title: "Moved to Paris to study at the Sorbonne", description: "Relocation and education" },
      "1894:1": { title: "Met Pierre Curie", description: "Collaboration" },
      "1898:1": { title: "Announced research on polonium and radium", description: "Scientific research" },
      "1903:1": { title: "Received the Nobel Prize in Physics and her doctorate", description: "Award and scholarship" },
      "1906:1": { title: "Became the Sorbonne's first woman professor", description: "Appointment and education" },
      "1911:1": { title: "Received the Nobel Prize in Chemistry in Stockholm", description: "Award" },
      "1914:1": { title: "Organised mobile X-ray services", description: "Medical technology" },
      "1921:1": { title: "Received one gram of radium in Washington", description: "Science and public activity" },
      "1929:1": { title: "Sought support for a radiology institute in Warsaw", description: "Science and public activity" },
      "1934:1": { title: "Died at Sallanches", description: "Death" },
    },
  },
  "mahatma-gandhi": {
    primaryField: "Politics",
    secondaryFields: ["Social movements", "Law", "Anti-colonialism", "Religious thought"],
    summary: "A leader of India's anti-colonial movement who developed nonviolent non-cooperation and mass organizing into globally influential political practice.",
    events: {
      "1869:1": { title: "Born in Porbandar", description: "Birth" },
      "1888:1": { title: "Went to London to study law", description: "Education" },
      "1891:1": { title: "Returned to India after qualifying as a barrister", description: "Return" },
      "1893:1": { title: "Arrived in Durban for legal work", description: "Relocation and law" },
      "1893:2": { title: "Suffered racial discrimination at Pietermaritzburg", description: "Political awakening memory site" },
      "1906:1": { title: "Organised nonviolent resistance in Johannesburg", description: "Social movement" },
      "1915:1": { title: "Returned to India and founded an ashram", description: "Social movement" },
      "1917:1": { title: "Led the Champaran satyagraha", description: "Social movement; regional centroid" },
      "1930:1": { title: "Salt march reached Dandi", description: "Social movement" },
      "1931:1": { title: "Attended the Round Table Conference in London", description: "Politics" },
      "1942:1": { title: "Quit India movement launched in Bombay", description: "Anti-colonial movement" },
      "1946:1": { title: "Conducted peace work in Noakhali", description: "Peace work; regional centroid" },
      "1948:1": { title: "Assassinated in New Delhi", description: "Death" },
    },
  },
  "alan-turing": {
    primaryField: "Science",
    secondaryFields: ["Mathematics", "Computer science", "Cryptanalysis", "Artificial intelligence", "Mathematical biology"],
    summary: "A British mathematician, cryptanalyst and computing pioneer whose work shaped computability, wartime codebreaking, computer design and machine intelligence.",
    events: {
      "1912:1": { title: "Born in Paddington, London", description: "Birth" },
      "1926:1": { title: "Entered Sherborne School", description: "Education" },
      "1931:1": { title: "Entered King's College, Cambridge", description: "Education" },
      "1936:1": { title: "Went to Princeton for doctoral study", description: "Education and research" },
      "1939:1": { title: "Joined wartime cryptanalysis at Bletchley Park", description: "Wartime research" },
      "1945:1": { title: "Proposed the ACE design at the National Physical Laboratory", description: "Computing research" },
      "1948:1": { title: "Joined the Manchester computing laboratory", description: "Appointment and research" },
      "1950:1": { title: "Published his paper on machine intelligence", description: "Artificial-intelligence research" },
      "1952:1": { title: "Convicted for a same-sex relationship and forcibly treated", description: "State persecution" },
      "1954:1": { title: "Died in Wilmslow", description: "Officially ruled suicide; circumstances remain discussed" },
    },
  },
};
