import type { PersonEnglishTranslation } from "./people-en.js";

export const peopleEnglish40Part1: Record<string, PersonEnglishTranslation> = {
  "cyrus-the-great": {
    primaryField: "Politics",
    secondaryFields: ["Imperial administration", "Military", "Law", "Religious policy"],
    summary: "Founder of the Achaemenid Empire, who built a vast western Asian empire through conquest and the integration of local institutions. His birth year, birthplace, and final battlefield cannot be fixed precisely.",
    events: {
      "-600:1": { title: "Approximately born in the Anshan region", description: "Birth year and place uncertain; Tall-e Malyan is only a regional anchor" },
      "-559:1": { title: "Succeeded as king of Anshan", description: "Approximate accession year; Pasargadae anchors the dynastic center" },
      "-550:1": { title: "Defeated the Median kingdom", description: "Took Ecbatana; the precise battle site is unknown" },
      "-547:1": { title: "Conquered Lydia", description: "Captured Sardis around 547 BCE; some chronologies use 546 BCE" },
      "-539:1": { title: "Entered Babylon", description: "Conquered Babylon and issued a royal declaration as its king" },
      "-530:1": { title: "Died on a northeastern campaign", description: "Ancient accounts conflict; the point is only a very rough lower-Oxus regional anchor" },
    },
  },
  ashoka: {
    primaryField: "Politics",
    secondaryFields: ["Buddhism", "Imperial administration", "Law", "Epigraphy"],
    summary: "Mauryan ruler who promoted dhamma, public governance, and religious tolerance through inscriptions after the Kalinga War. His birth, accession chronology, and parts of his itinerary are later reconstructions.",
    events: {
      "-304:1": { title: "Traditionally born in the Mauryan heartland", description: "Date and place are insecure; Pataliputra is a conventional regional anchor" },
      "-286:1": { title: "Traditionally posted at Ujjain", description: "Reported in later Buddhist biographies; the year is approximate" },
      "-268:1": { title: "Approximate accession", description: "A common modern chronology; some traditions place accession earlier" },
      "-261:1": { title: "Kalinga War", description: "Later edicts record remorse over killing and deportation; Dhauli anchors the event" },
      "-258:1": { title: "Issues rock edicts", description: "Edicts spread from roughly mid-reign; the exact starting year is uncertain" },
      "-250:1": { title: "Supports Buddhist building at Sanchi", description: "The early stupa is traditionally assigned to his reign; construction date and personal presence are uncertain" },
      "-249:1": { title: "Pilgrimage to Lumbini", description: "The pillar inscription records a visit in his twentieth regnal year" },
      "-249:2": { title: "Associated pillar at Sarnath", description: "The pillar association is secure, but a precise personal itinerary is not" },
      "-232:1": { title: "Traditionally dies at Pataliputra", description: "Death is usually dated around 232 BCE; the location depends mainly on later tradition" },
    },
  },
  "julius-caesar": {
    primaryField: "Politics",
    secondaryFields: ["Military", "Law", "Literature", "State institutions"],
    summary: "Roman commander, politician, and author whose conquest of Gaul, civil-war victory, dictatorship, and assassination accelerated the Republic's transformation into imperial rule.",
    events: {
      "-100:1": { title: "Born in Rome", description: "The exact residence cannot be located" },
      "-81:1": { title: "Serves in Asia Minor", description: "Participated in the siege of Mytilene around this time; sources vary slightly on the year" },
      "-69:1": { title: "Quaestor in Hispania", description: "Córdoba anchors the province's main administrative center" },
      "-58:1": { title: "Begins the Gallic Wars", description: "Defeats the Helvetii; the Bibracte battlefield is approximate" },
      "-52:1": { title: "Siege of Alesia", description: "Defeats Vercingetorix; the battlefield covers a broad area" },
      "-49:1": { title: "Crosses the Rubicon", description: "Civil war begins; the ancient river's precise course is disputed" },
      "-48:1": { title: "Victory at Pharsalus", description: "Defeats Pompey's main army; battlefield point approximate" },
      "-48:2": { title: "Arrives in Alexandria", description: "Pursues Pompey and enters the Ptolemaic dynastic conflict" },
      "-46:1": { title: "Battle of Thapsus", description: "Defeats the remaining main republican force; town and battlefield are approximate" },
      "-44:1": { title: "Assassinated at a Senate meeting", description: "Killed on March 15 in the complex of Pompey's Theatre" },
    },
  },
  augustus: {
    primaryField: "Politics",
    secondaryFields: ["Imperial administration", "Military", "Law", "Urban development"],
    summary: "Rome's first emperor, who reorganized power under republican forms after civil war and established the principate that endured for centuries.",
    events: {
      "-63:1": { title: "Born in Rome", description: "Born near the Palatine; identification of a specific house is not certain" },
      "-44:1": { title: "Learns of his inheritance at Apollonia", description: "Learns that Caesar adopted him as heir and returns to Italy" },
      "-42:1": { title: "Battles of Philippi", description: "Joins Antony in defeating Brutus and Cassius" },
      "-31:1": { title: "Battle of Actium", description: "Defeats Antony and Cleopatra's fleet; the point approximates the battle area" },
      "-30:1": { title: "Takes Alexandria", description: "Egypt comes under Roman control" },
      "-27:1": { title: "Receives the title Augustus", description: "Conventionally marks the formal beginning of the principate" },
      "14:1": { title: "Dies at Nola", description: "Succeeded by Tiberius" },
    },
  },
  "constantine-i": {
    primaryField: "Politics",
    secondaryFields: ["Religious policy", "Military", "Law", "Urban development"],
    summary: "Roman emperor who reunited the empire, granted Christianity legal standing, and founded Constantinople. The project uses the conventional but uncertain birth year of 272.",
    events: {
      "272:1": { title: "Approximately born at Naissus", description: "Conventionally dated to 272; ancient evidence does not establish an exact year" },
      "306:1": { title: "Proclaimed emperor at York", description: "Acclaimed by the army after his father's death" },
      "312:1": { title: "Battle of the Milvian Bridge", description: "Defeats Maxentius; later vision narratives pose source-critical problems" },
      "313:1": { title: "Religious settlement at Milan", description: "Agrees with Licinius on toleration, later called the Edict of Milan" },
      "324:1": { title: "Victory at Chrysopolis", description: "Defeats Licinius and becomes sole ruler" },
      "325:1": { title: "Convenes the Council of Nicaea", description: "Calls bishops together over doctrine and church unity" },
      "330:1": { title: "Dedicates Constantinople", description: "Expands Byzantium into a new imperial capital" },
      "337:1": { title: "Dies near Nicomedia", description: "Baptized near the end of his life; exact site unknown" },
    },
  },
  "suleiman-the-magnificent": {
    primaryField: "Politics",
    secondaryFields: ["Law", "Military", "Imperial administration", "Arts patronage"],
    summary: "Ottoman sultan who expanded power in the Balkans, Mediterranean, and western Asia, consolidated law, and sponsored the arts. His birth is dated to 1494 or 1494/95.",
    events: {
      "1494:1": { title: "Approximately born at Trabzon", description: "Usually dated to 1494 or 1494/95" },
      "1520:1": { title: "Accedes at Istanbul", description: "Succeeds to the sultanate" },
      "1521:1": { title: "Captures Belgrade", description: "Takes the strategic Danubian fortress" },
      "1522:1": { title: "Conquers Rhodes", description: "Forces the Knights Hospitaller to evacuate after a siege" },
      "1526:1": { title: "Battle of Mohács", description: "Defeats the Hungarian royal army; battlefield point approximate" },
      "1529:1": { title: "First siege of Vienna", description: "Withdraws after an unsuccessful siege" },
      "1534:1": { title: "Enters Baghdad", description: "Takes the city during war with the Safavids" },
      "1555:1": { title: "Peace of Amasya", description: "Temporarily defines Ottoman–Safavid frontiers and spheres" },
      "1566:1": { title: "Dies during the siege of Szigetvár", description: "Dies on his final Hungarian campaign; news is temporarily concealed" },
    },
  },
  "george-washington": {
    primaryField: "Politics",
    secondaryFields: ["Military", "State-building", "Agriculture", "Surveying"],
    summary: "Commander of the Continental Army, president of the Constitutional Convention, and first U.S. president, who set major republican precedents while also owning and exploiting enslaved people.",
    events: {
      "1732:1": { title: "Born at Popes Creek", description: "Born on a plantation in colonial Virginia" },
      "1753:1": { title: "Mission to Fort Le Boeuf", description: "Carries the Virginia governor's demand; the map marks the endpoint of a long route" },
      "1754:1": { title: "Defeat at Fort Necessity", description: "Surrenders early in the French and Indian conflict" },
      "1775:1": { title: "Appointed commander in chief", description: "Appointed by the Continental Congress in Philadelphia" },
      "1776:1": { title: "Battle of Trenton", description: "Wins after crossing the Delaware" },
      "1777:1": { title: "Winter at Valley Forge", description: "The army endures winter and reorganizes its training" },
      "1781:1": { title: "Victory at Yorktown", description: "American and French forces compel Cornwallis to surrender" },
      "1787:1": { title: "Presides over the Constitutional Convention", description: "Chairs the drafting convention in Philadelphia" },
      "1789:1": { title: "Inaugurated as first president", description: "Takes the oath at Federal Hall in New York" },
      "1797:1": { title: "Returns to Mount Vernon", description: "Voluntarily leaves office after two terms" },
      "1799:1": { title: "Dies at Mount Vernon", description: "The estate's operation depended on enslaved labor" },
    },
  },
  "simon-bolivar": {
    primaryField: "Politics",
    secondaryFields: ["Military", "State-building", "Anticolonial movements", "Political thought"],
    summary: "Venezuelan independence leader and commander who drove emancipation from Spanish rule across much of northern and western South America and helped create Gran Colombia.",
    events: {
      "1783:1": { title: "Born in Caracas", description: "Born into a wealthy Creole family" },
      "1805:1": { title: "Oath in Rome", description: "The Monte Sacro oath's wording comes from later recollection and is traditional" },
      "1811:1": { title: "Participates in Venezuelan independence", description: "Supports the First Republic" },
      "1812:1": { title: "Issues the Cartagena Manifesto", description: "Analyzes the First Republic's failure and argues for continued war" },
      "1815:1": { title: "Writes the Jamaica Letter", description: "Sets out a vision of independence while exiled in Kingston" },
      "1816:1": { title: "Organizes an expedition from Haiti", description: "Prepares to return from Les Cayes with Pétion's support" },
      "1819:1": { title: "Congress of Angostura", description: "Presents a plan of government" },
      "1819:2": { title: "Battle of Boyacá", description: "Wins a decisive victory" },
      "1821:1": { title: "Battle of Carabobo", description: "Consolidates independence across most of Venezuela" },
      "1824:1": { title: "Leads the Peruvian campaign from Lima", description: "Organizes the campaign; Sucre commands in person at Ayacucho" },
      "1830:1": { title: "Dies near Santa Marta", description: "Dies after relinquishing political power" },
    },
  },
  "abraham-lincoln": {
    primaryField: "Politics",
    secondaryFields: ["Law", "State-building", "War leadership", "Abolition"],
    summary: "Sixteenth U.S. president, who preserved the Union through civil war, advanced emancipation and constitutional abolition, and was assassinated near the war's end.",
    events: {
      "1809:1": { title: "Born at Sinking Spring Farm, Kentucky", description: "Born near present-day Hodgenville" },
      "1816:1": { title: "Family moves to Indiana", description: "Moves near present-day Gentryville during childhood" },
      "1831:1": { title: "Settles at New Salem", description: "Begins an independent life and public career" },
      "1837:1": { title: "Moves to Springfield", description: "Practices after qualifying as an attorney" },
      "1858:1": { title: "Delivers the House Divided speech", description: "Also participates in the Lincoln–Douglas debates that year" },
      "1861:1": { title: "Inaugurated president", description: "Takes office in Washington; civil war begins weeks later" },
      "1862:1": { title: "Issues the preliminary Emancipation Proclamation", description: "Announces emancipation in areas in rebellion from the next year" },
      "1863:1": { title: "Gettysburg Address", description: "Reframes the war around Union, equality, and democratic government" },
      "1865:1": { title: "Assassinated at Ford's Theatre", description: "Shot and dies the next morning at the Petersen House" },
    },
  },
  "franklin-d-roosevelt": {
    primaryField: "Politics",
    secondaryFields: ["Economic policy", "War leadership", "Diplomacy", "Social security"],
    summary: "Thirty-second U.S. president, who expanded federal capacity through the New Deal and led through most of World War II; his administration also forcibly removed and incarcerated Japanese Americans.",
    events: {
      "1882:1": { title: "Born at Hyde Park", description: "Born at the Springwood estate" },
      "1900:1": { title: "Enters Harvard", description: "Studies history in Cambridge" },
      "1910:1": { title: "Elected to the New York State Senate", description: "The state capitol in Albany anchors the event" },
      "1913:1": { title: "Becomes Assistant Secretary of the Navy", description: "Serves in the Wilson administration until 1920" },
      "1921:1": { title: "Falls ill at Campobello", description: "Left permanently paralyzed; diagnosed then as polio, though later research has discussed alternatives" },
      "1928:1": { title: "Elected governor of New York", description: "State relief programs help inform the later New Deal" },
      "1933:1": { title: "Inaugurated and launches the New Deal", description: "Advances banking, relief, and public-works measures in the first hundred days" },
      "1941:1": { title: "Leads U.S. entry into war after Pearl Harbor", description: "Requests a declaration of war before Congress" },
      "1943:1": { title: "Tehran Conference", description: "Coordinates war and postwar planning with Churchill and Stalin" },
      "1945:1": { title: "Yalta Conference", description: "Discusses postwar Europe and the proposed United Nations" },
      "1945:2": { title: "Dies at Warm Springs", description: "Dies of a cerebral hemorrhage on April 12" },
    },
  },
  "vladimir-lenin": {
    primaryField: "Politics",
    secondaryFields: ["Revolutionary theory", "State-building", "Economic policy", "Publishing"],
    summary: "Bolshevik leader and first head of the Soviet government, who seized power in 1917 and built a one-party state amid civil war, political repression, and institutionalized violence.",
    events: {
      "1870:1": { title: "Born in Simbirsk", description: "Present-day Ulyanovsk" },
      "1887:1": { title: "Studies and is arrested at Kazan", description: "Arrested and expelled after a student protest" },
      "1893:1": { title: "Moves to Saint Petersburg", description: "Joins Marxist circles and organizes among workers" },
      "1897:1": { title: "Exiled to Shushenskoye", description: "Spends three years in Siberian exile" },
      "1900:1": { title: "Organizes Iskra in Europe", description: "Munich represents an early editorial center" },
      "1903:1": { title: "Second Congress of the Russian Social Democratic Labour Party", description: "Moves from Brussels to London and produces the factional split" },
      "1917:1": { title: "Leaves Zurich for Russia", description: "Ends exile after the February Revolution; this is the departure point" },
      "1917:2": { title: "Arrives in Petrograd", description: "Arrives at Finland Station and advances a radical program" },
      "1917:3": { title: "Bolsheviks seize power", description: "Overthrows the Provisional Government and heads the new government" },
      "1918:1": { title: "Government moves to Moscow", description: "Moves the capital and leaves the world war by treaty" },
      "1924:1": { title: "Dies at Gorki", description: "Dies after several strokes" },
    },
  },
  "adolf-hitler": {
    primaryField: "Politics",
    secondaryFields: ["Totalitarianism", "War", "Racism", "Propaganda"],
    summary: "Nazi leader and German dictator whose racism, antisemitism, and expansionism drove European war and systematic mass murder, including six million Jews and millions of other victims.",
    events: {
      "1889:1": { title: "Born at Braunau am Inn", description: "Born in an Austro-Hungarian border town" },
      "1908:1": { title: "Moves to Vienna", description: "His later claim that his antisemitism fully formed there is not supported by the evidence" },
      "1913:1": { title: "Moves to Munich", description: "Leaves Vienna in May" },
      "1914:1": { title: "Serves in World War I", description: "The point marks his unit's First Ypres area, not an exact personal position" },
      "1919:1": { title: "Joins the German Workers' Party", description: "The organization is later renamed the Nazi Party" },
      "1923:1": { title: "Launches the Beer Hall Putsch", description: "The failed coup causes deaths and injuries" },
      "1924:1": { title: "Imprisoned at Landsberg", description: "Receives a lenient treason sentence and writes his political manifesto" },
      "1933:1": { title: "Appointed German chancellor", description: "The Nazis then dismantle democracy and establish dictatorship" },
      "1939:1": { title: "Launches war in Europe", description: "Directs the invasion of Poland from Berlin; the point does not imply front-line presence" },
      "1941:1": { title: "Directs the eastern war from the Wolf's Lair", description: "War against the Soviet Union escalates alongside Nazi extermination policies" },
      "1945:1": { title: "Dies by suicide in the Berlin bunker", description: "Dies as Germany collapses and Soviet forces enter Berlin" },
    },
  },
  "mao-zedong": {
    primaryField: "Politics",
    secondaryFields: ["Revolutionary theory", "Military", "State-building", "Literature"],
    summary: "Principal CCP founder and central founding leader of the People's Republic of China; his Great Leap Forward and Cultural Revolution caused mass famine, persecution, and social destruction.",
    events: {
      "1893:1": { title: "Born at Shaoshan", description: "Born at Shaoshan in Xiangtan, Hunan" },
      "1911:1": { title: "Joins revolutionary forces in Changsha", description: "Serves briefly during the 1911 Revolution" },
      "1918:1": { title: "Works at Peking University Library", description: "Encounters New Culture and Marxist circles" },
      "1921:1": { title: "Attends the CCP First National Congress", description: "Meets in Shanghai; the final session moves to Jiaxing, while the map uses the starting point" },
      "1927:1": { title: "Establishes a base in the Jinggang Mountains", description: "Develops a revolutionary strategy centered on rural bases" },
      "1935:1": { title: "Leadership rises after the Zunyi Conference", description: "Strengthens his military and political position during the Long March" },
      "1936:1": { title: "Reaches the Yan'an region", description: "Yan'an becomes the revolutionary political center" },
      "1949:1": { title: "Proclaims the People's Republic of China", description: "Proclaims the new state in Beijing on October 1" },
      "1958:1": { title: "Launches the Great Leap Forward", description: "Policy, coercive procurement, and distorted reporting cause catastrophic famine and tens of millions of deaths" },
      "1966:1": { title: "Launches the Cultural Revolution", description: "Causes prolonged persecution, violence, educational disruption, and institutional damage" },
      "1972:1": { title: "Meets Nixon", description: "U.S.–China rapprochement alters the Cold War strategic balance" },
      "1976:1": { title: "Dies in Beijing", description: "Dies on September 9" },
    },
  },
  plato: {
    primaryField: "Thought and education",
    secondaryFields: ["Philosophy", "Political thought", "Ethics", "Epistemology", "Education"],
    summary: "Ancient Greek philosopher whose dialogues examined knowledge, ethics, politics, and metaphysics and whose Academy formed a lasting intellectual tradition. Dates and some journeys are disputed conventional anchors.",
    events: {
      "-428:1": { title: "Approximately born in Athens", description: "Usually dated 428/427 BCE; other years and an Aegina tradition also exist" },
      "-407:1": { title: "Approximately associates with Socrates", description: "No exact starting year for his participation can be established" },
      "-399:1": { title: "Execution of Socrates", description: "Decisively shapes Plato's philosophical and political thought" },
      "-399:2": { title: "Traditionally stays at Megara", description: "Reported by the much later Diogenes Laertius and treated as a traditional itinerary" },
      "-388:1": { title: "First journey to Syracuse", description: "Visits around 388/387 BCE and meets Dion" },
      "-387:1": { title: "Establishes the Academy at Athens", description: "The community forms gradually, not by formal incorporation on one day" },
      "-367:1": { title: "Second journey to Syracuse", description: "Unsuccessfully attempts to influence Dionysius II's rule" },
      "-361:1": { title: "Third journey to Syracuse", description: "Leaves a political impasse with help from friends" },
      "-347:1": { title: "Approximately dies in Athens", description: "Dated around 348/347 BCE; the traditional grave has not been confirmed" },
    },
  },
};
