import type { PersonEnglishTranslation } from "./people-en.js";

export const peopleEnglish40Part2: Record<string, PersonEnglishTranslation> = {
  "ibn-khaldun": {
    primaryField: "Economic and social thought",
    secondaryFields: ["History", "Political thought", "Social theory", "Law"],
    summary: "A Maghribi historian, jurist and political practitioner whose Muqaddimah systematically analyzed states, group solidarity, economy and dynastic change. Medieval locations are modern approximations.",
    events: {
      "1332:1": { title: "Born in Tunis", description: "Born in Tunis under Hafsid rule" },
      "1354:1": { title: "Entered court service in Fez", description: "Approximate year; later caught in court struggles and imprisoned" },
      "1363:1": { title: "Arrived in Granada", description: "Entered the Nasrid court" },
      "1364:1": { title: "Diplomatic mission to Seville", description: "Negotiated with Peter I of Castile for Granada" },
      "1365:1": { title: "Served in Bejaia", description: "Held high court office; translations of the title vary" },
      "1375:1": { title: "Retreat and composition of the Muqaddimah", description: "Stayed near Qal'at Ibn Salama circa 1375–1378; site point approximate" },
      "1378:1": { title: "Returned to Tunis", description: "Continued revising his historical work" },
      "1382:1": { title: "Moved to Cairo", description: "Taught and repeatedly served as a Maliki judge" },
      "1387:1": { title: "Pilgrimage to Mecca", description: "Completed the pilgrimage during his Egyptian period" },
      "1401:1": { title: "Met Timur at Damascus", description: "Met Timur during the siege, an episode recorded in his autobiography" },
      "1406:1": { title: "Died in Cairo", description: "Death" },
    },
  },
  "niccolo-machiavelli": {
    primaryField: "Economic and social thought",
    secondaryFields: ["Political thought", "Diplomacy", "History", "Literature"],
    summary: "A Florentine diplomat, historian and political thinker who used republican experience to analyze power and statecraft.",
    events: {
      "1469:1": { title: "Born in Florence", description: "Birth" },
      "1498:1": { title: "Appointed republican secretary", description: "Began extensive diplomatic service for Florence" },
      "1500:1": { title: "Mission to the French court", description: "Lyon is an approximate anchor for the itinerant court" },
      "1502:1": { title: "Observed Cesare Borgia", description: "Diplomatic mission in Romagna" },
      "1512:1": { title: "Removed after the republic fell", description: "Lost office after the Medici restoration" },
      "1513:1": { title: "Wrote The Prince near San Casciano", description: "Withdrew to his estate after release" },
      "1520:1": { title: "Commissioned to write Florentine Histories", description: "Commissioned by Cardinal Giulio de' Medici" },
      "1525:1": { title: "Presented the history in Rome", description: "Presented it to the patron, now Pope Clement VII" },
      "1527:1": { title: "Died in Florence", description: "Death" },
    },
  },
  "john-locke": {
    primaryField: "Thought and education",
    secondaryFields: ["Political thought", "Epistemology", "Medicine", "Religious toleration"],
    summary: "An English philosopher, medical researcher and political thinker known for empiricism, natural rights, toleration and limited government.",
    events: {
      "1632:1": { title: "Born at Wrington", description: "Born in Somerset, England" },
      "1647:1": { title: "Entered Westminster School", description: "Education in London" },
      "1652:1": { title: "Entered Oxford", description: "Studied at Christ Church and later pursued medicine and experiments" },
      "1667:1": { title: "Joined Shaftesbury's household", description: "Worked in London as physician, adviser and administrator" },
      "1675:1": { title: "Stayed in Montpellier", description: "Studied medicine and French religious life" },
      "1683:1": { title: "Exile in the Netherlands", description: "Amsterdam is an anchor; his residences changed" },
      "1689:1": { title: "Returned and published major works", description: "Returned after the Glorious Revolution" },
      "1691:1": { title: "Moved to Oates", description: "High Laver is an approximate location for the estate" },
      "1704:1": { title: "Died at Oates", description: "Death" },
    },
  },
  "jean-jacques-rousseau": {
    primaryField: "Thought and education",
    secondaryFields: ["Political thought", "Education", "Literature", "Music"],
    summary: "A Geneva-born philosopher and writer whose ideas on popular sovereignty, the general will, education and civilization profoundly shaped modern politics.",
    events: {
      "1712:1": { title: "Born in Geneva", description: "Born in the independent Calvinist city-state" },
      "1728:1": { title: "Travelled to Turin and converted", description: "Left Geneva and converted to Catholicism" },
      "1731:1": { title: "Returned to Chambéry", description: "Returned to Madame de Warens and lived nearby for much of the decade" },
      "1740:1": { title: "Tutor in Lyon", description: "Entered Enlightenment intellectual circles" },
      "1742:1": { title: "Presented a notation system in Paris", description: "The Academy rejected his numerical music notation" },
      "1743:1": { title: "Secretary at the embassy in Venice", description: "Brief diplomatic employment" },
      "1762:1": { title: "The Social Contract and Emile published", description: "Both were condemned, forcing him to flee" },
      "1762:2": { title: "Refuge at Môtiers", description: "Within-year movement sequence is approximate" },
      "1766:1": { title: "Took refuge in England", description: "Stayed near Wootton at David Hume's invitation" },
      "1767:1": { title: "Returned to France", description: "Paris is used as a later-life writing anchor" },
      "1778:1": { title: "Died at Ermenonville", description: "Death" },
    },
  },
  "mary-wollstonecraft": {
    primaryField: "Thought and education",
    secondaryFields: ["Women's rights", "Political thought", "Education", "Literature"],
    summary: "An English writer and political philosopher whose Vindication of the Rights of Woman argued for women's rational agency, education and civic standing.",
    events: {
      "1759:1": { title: "Born in Spitalfields, London", description: "Born on Primrose Street" },
      "1784:1": { title: "Founded a school at Newington Green", description: "Entered a circle of religious dissenters and radicals" },
      "1785:1": { title: "Travelled to Lisbon", description: "Cared for her gravely ill friend Fanny Blood" },
      "1787:1": { title: "Began professional writing in London", description: "Worked as author, translator and reviewer" },
      "1792:1": { title: "Published A Vindication of the Rights of Woman", description: "Publication in London" },
      "1792:2": { title: "Moved to revolutionary Paris", description: "Witnessed the Revolution's radical phase" },
      "1795:1": { title: "Journey through Scandinavia", description: "Gothenburg is a representative first anchor for the multi-country journey" },
      "1796:1": { title: "Returned to London", description: "Resumed writing and intellectual life" },
      "1797:1": { title: "Died in London", description: "Died from puerperal infection after childbirth" },
    },
  },
  "john-maynard-keynes": {
    primaryField: "Economic and social thought",
    secondaryFields: ["Macroeconomics", "Public policy", "International finance", "Government"],
    summary: "A British economist and public official who reshaped modern macroeconomics through aggregate-demand theory and helped design the Bretton Woods order.",
    events: {
      "1883:1": { title: "Born in Cambridge", description: "Born on Harvey Road" },
      "1897:1": { title: "Entered Eton", description: "Secondary education" },
      "1902:1": { title: "Entered King's College, Cambridge", description: "Entered as a scholar" },
      "1906:1": { title: "Joined the India Office", description: "British public service in London" },
      "1915:1": { title: "Joined the Treasury", description: "Worked on international finance during the First World War" },
      "1919:1": { title: "Resigned from the Paris Peace Conference", description: "Opposed the reparations settlement" },
      "1936:1": { title: "Published The General Theory", description: "Cambridge is the publication-period anchor" },
      "1941:1": { title: "Negotiated wartime finance in Washington", description: "Worked on Lend-Lease and postwar arrangements" },
      "1944:1": { title: "Led at Bretton Woods", description: "Helped design the IMF and World Bank framework" },
      "1946:1": { title: "Died at Tilton", description: "Firle is an approximate location for the estate" },
    },
  },
  archimedes: {
    primaryField: "Science",
    secondaryFields: ["Mathematics", "Mechanics", "Engineering", "Astronomy"],
    summary: "An ancient Greek mathematician and engineer whose foundational work spanned geometry, statics, hydrostatics and machines. His dates and most life events are approximate.",
    events: {
      "-287:1": { title: "Approximate birth in Syracuse", description: "Traditional approximate year; exact birth year unknown" },
      "-270:1": { title: "Possible study in Alexandria", description: "Inferred from later biography and scholarly connections; not securely attested" },
      "-260:1": { title: "Research in Syracuse", description: "Approximate anchor for work associated with Syracuse" },
      "-250:1": { title: "Work on levers and floating bodies", description: "Approximate mature-work anchor; the Eureka story is not treated as exact history" },
      "-240:1": { title: "Sent theorems to Alexandrian colleagues", description: "Prefaces attest correspondence; year is only a sequence anchor" },
      "-214:1": { title: "Defence of Syracuse", description: "Later accounts may exaggerate details of his machines" },
      "-212:1": { title: "Killed during the capture of Syracuse", description: "Ancient sources give several versions of his death" },
    },
  },
  "al-khwarizmi": {
    primaryField: "Science",
    secondaryFields: ["Mathematics", "Astronomy", "Geography", "Computation"],
    summary: "An Abbasid-era mathematician, astronomer and geographer whose algebra and work with Hindu-Arabic numerals gave the world the terms algebra and algorithm. His birthplace and exact dates are unknown.",
    events: {
      "780:1": { title: "Approximate birth; place unknown", description: "Baghdad is a conservative display anchor; birth in Khwarazm is unproven" },
      "813:1": { title: "Approximate entry into Baghdad scholarship", description: "Exact appointment date is unknown" },
      "820:1": { title: "Approximate composition of the algebra", description: "Composed around this period; exact year unknown" },
      "825:1": { title: "Work on astronomical tables", description: "Approximate anchor for work in Baghdad" },
      "833:1": { title: "Geographical work", description: "Approximate late-al-Ma'mun anchor for coordinate tables" },
      "850:1": { title: "Approximate death; place unknown", description: "Baghdad is retained as the last known activity centre, not asserted as place of death" },
    },
  },
  "ibn-al-haytham": {
    primaryField: "Science",
    secondaryFields: ["Optics", "Mathematics", "Astronomy", "Experimental method"],
    summary: "A mathematician and optical scientist in the Arabic scholarly tradition whose work on vision, reflection, refraction and experimental demonstration transformed optics. Biographical traditions conflict and his dates are approximate.",
    events: {
      "965:1": { title: "Approximate birth in Basra", description: "The source qualifies Basra as a possible birthplace" },
      "990:1": { title: "Turned from office to science in Basra", description: "Approximate anchor from conflicting biographies" },
      "1000:1": { title: "Approximate move to Egypt", description: "Invited under the Fatimids; exact date unknown" },
      "1001:1": { title: "Surveyed the upper Nile", description: "Aswan, route and year are approximate" },
      "1011:1": { title: "Optical research in Cairo", description: "Approximate anchor for work during and around restricted residence" },
      "1027:1": { title: "Wrote an intellectual autobiography", description: "The surviving account concerns ideas rather than detailed life events" },
      "1040:1": { title: "Approximate death in Cairo", description: "Commonly dated about 1040; 1039 is also reported" },
    },
  },
  "johannes-kepler": {
    primaryField: "Science",
    secondaryFields: ["Astronomy", "Mathematics", "Optics", "Physics"],
    summary: "A German astronomer and mathematician whose laws of planetary motion established elliptical orbits and quantitative celestial physics.",
    events: {
      "1571:1": { title: "Born in Weil der Stadt", description: "Birth" },
      "1589:1": { title: "Entered the University of Tübingen", description: "Studied theology, mathematics and Copernican astronomy" },
      "1594:1": { title: "Took a post in Graz", description: "Worked as mathematics teacher and calendar maker" },
      "1600:1": { title: "Joined Tycho Brahe near Prague", description: "Left Graz under religious pressure" },
      "1609:1": { title: "Published Astronomia Nova in Prague", description: "Presented the first two planetary laws" },
      "1612:1": { title: "Moved to Linz", description: "Became district mathematician" },
      "1619:1": { title: "Published Harmonices Mundi", description: "Presented the third planetary law" },
      "1627:1": { title: "Printed the Rudolphine Tables in Ulm", description: "High-precision tables based on Tycho's observations and Kepler's theory" },
      "1630:1": { title: "Died in Regensburg", description: "Died while travelling" },
    },
  },
  "michael-faraday": {
    primaryField: "Science",
    secondaryFields: ["Physics", "Chemistry", "Electrical engineering", "Science communication"],
    summary: "An English experimental scientist whose work on electromagnetic rotation, induction, electrochemistry and fields laid experimental foundations for modern electrical technology.",
    events: {
      "1791:1": { title: "Born at Newington Butts", description: "Near modern Elephant and Castle in London" },
      "1805:1": { title: "Began bookbinding apprenticeship", description: "Educated himself in science through books" },
      "1813:1": { title: "Hired by the Royal Institution", description: "Humphry Davy hired him as laboratory assistant" },
      "1814:1": { title: "Continental tour with Davy", description: "Paris is a representative point on a multi-country journey" },
      "1821:1": { title: "Demonstrated electromagnetic rotation", description: "Built an early motor-principle apparatus" },
      "1825:1": { title: "Isolated benzene and became laboratory director", description: "Research and appointment at the Royal Institution" },
      "1831:1": { title: "Discovered electromagnetic induction", description: "Showed that changing magnetic conditions induce current" },
      "1845:1": { title: "Discovered the magneto-optical effect", description: "Connected magnetism and polarized light" },
      "1867:1": { title: "Died near Hampton Court", description: "Died in his grace-and-favour residence" },
    },
  },
  "james-clerk-maxwell": {
    primaryField: "Science",
    secondaryFields: ["Physics", "Mathematics", "Optics", "Thermodynamics"],
    summary: "A Scottish mathematical physicist who unified electricity, magnetism and light, while making foundational contributions to kinetic theory, color and statistical physics.",
    events: {
      "1831:1": { title: "Born in Edinburgh", description: "Born at 14 India Street" },
      "1834:1": { title: "Childhood at Glenlair", description: "Approximate year and location for the family move" },
      "1847:1": { title: "Entered the University of Edinburgh", description: "Studied natural philosophy, mathematics and chemistry" },
      "1850:1": { title: "Moved to Cambridge", description: "Entered Peterhouse and then Trinity College" },
      "1856:1": { title: "Professor at Aberdeen", description: "Studied the stability of Saturn's rings" },
      "1860:1": { title: "Professor at King's College London", description: "Developed electromagnetic field theory" },
      "1865:1": { title: "Returned to Glenlair", description: "Developed the theory later presented in his electromagnetic treatise" },
      "1871:1": { title: "First Cavendish Professor", description: "Established and led the Cavendish Laboratory" },
      "1879:1": { title: "Died in Cambridge", description: "Death" },
    },
  },
  "louis-pasteur": {
    primaryField: "Medicine",
    secondaryFields: ["Microbiology", "Chemistry", "Vaccines", "Public health"],
    summary: "A French chemist and pioneer of microbiology whose work on fermentation, germ theory, pasteurization and vaccines transformed medicine, food safety and public health.",
    events: {
      "1822:1": { title: "Born in Dole", description: "Born in the French Jura" },
      "1827:1": { title: "Family moved to Arbois", description: "Year follows the Institut Pasteur timeline" },
      "1843:1": { title: "Entered the École Normale Supérieure", description: "Studied chemistry and physics in Paris" },
      "1848:1": { title: "Faculty appointment in Strasbourg", description: "Academic appointment" },
      "1854:1": { title: "Dean of science at Lille", description: "Connected fermentation research with industrial problems" },
      "1857:1": { title: "Returned to Paris and established a laboratory", description: "Continued work on fermentation and microorganisms" },
      "1865:1": { title: "Studied silkworm disease at Alès", description: "A multi-year investigation for French sericulture" },
      "1881:1": { title: "Anthrax vaccine demonstration at Pouilly-le-Fort", description: "Public animal trial; preparation details remain historically discussed" },
      "1885:1": { title: "First celebrated rabies treatment", description: "Historical methods and ethics require period context" },
      "1888:1": { title: "Institut Pasteur opened", description: "Established in Paris through international subscription" },
      "1895:1": { title: "Died at Marnes-la-Coquette", description: "Died at the Villeneuve-l'Étang estate" },
    },
  },
};
