import type { PoliticalEntity } from "@geograph/domain";

const chineseOverrides: Record<string, string> = {
  "Antigua and Barbuda": "安提瓜和巴布达",
  "Bosnia and Herzegovina": "波斯尼亚和黑塞哥维那",
  Burma: "缅甸",
  Byelarus: "白俄罗斯",
  Congo: "刚果（布）",
  "Czech Republic": "捷克",
  "Gambia, The": "冈比亚",
  "Hong Kong": "中国香港",
  "Ivory Coast": "科特迪瓦",
  "Korea, Democratic People's Republic of": "朝鲜",
  "Korea, Republic of": "韩国",
  Macedonia: "北马其顿",
  "Netherlands Antilles": "荷属安的列斯",
  "Rapa Nui": "拉帕努伊",
  "Saint Barthelemy": "圣巴泰勒米",
  "Saint Kitts and Nevis": "圣基茨和尼维斯",
  "Saint Lucia": "圣卢西亚",
  "Saint Martin": "法属圣马丁",
  "Saint Vincent and the Grenadines": "圣文森特和格林纳丁斯",
  Swaziland: "斯威士兰",
  "Tanzania, United Republic of": "坦桑尼亚",
  Trinidad: "特立尼达",
  Turkey: "土耳其",
  "Turkish Cypriot-administered area": "北塞浦路斯土耳其共和国",
  "Turks and Caicos Islands": "特克斯和凯科斯群岛",
  "United States Virgin Islands": "美属维尔京群岛",
  "Wallis and Futuna Islands": "瓦利斯和富图纳群岛",
  Zaire: "扎伊尔",

  Africa: "非洲",
  Arabia: "阿拉伯",
  "Abbasid Caliphate": "阿拔斯王朝",
  "Achaemenid Empire": "阿契美尼德帝国",
  "Almohad Caliphate": "穆瓦希德王朝",
  "Angevin Empire": "安茹帝国",
  Anasazi: "祖先普韦布洛人",
  "Ato trading confederacy": "阿托贸易联盟",
  "Assyria": "亚述",
  "Austrian Empire": "奥地利帝国",
  "Austria Hungary": "奥匈帝国",
  Babylonia: "巴比伦尼亚",
  Bactria: "巴克特里亚",
  "Bagan": "蒲甘王朝",
  Balhae: "渤海国",
  "Batavian Republic": "巴达维亚共和国",
  "British East India Company": "英国东印度公司",
  "British Raj": "英属印度",
  "Byzantine Empire": "拜占庭帝国",
  Carthage: "迦太基",
  "Carthaginian Empire": "迦太基帝国",
  "Carolingian Empire": "加洛林帝国",
  Castile: "卡斯蒂利亚王国",
  Castilla: "卡斯蒂利亚王国",
  "Chagatai Khanate": "察合台汗国",
  "Chalukya Empire": "遮娄其帝国",
  Champa: "占婆",
  "Chinese warlords": "中国军阀",
  "Chimariko (territory)": "奇马里科领地",
  "Chola state": "朱罗王朝",
  Cholas: "朱罗王朝",
  Chukchi: "楚科奇人",
  "Crimean Khanate": "克里米亚汗国",
  Dacia: "达契亚",
  "Duchy of Swabia": "施瓦本公国",
  "Dutch East Indies": "荷属东印度",
  "Dutch Formosa": "荷属台湾",
  "Eastern Roman Empire": "东罗马帝国",
  "English territory": "英格兰领地",
  Elam: "埃兰",
  "Emirate of Córdoba": "科尔多瓦酋长国",
  "Empire of Japan": "大日本帝国",
  "Fatimid Caliphate": "法蒂玛王朝",
  "Frankish Kingdom": "法兰克王国",
  Franks: "法兰克人",
  "French Indo-China": "法属印度支那",
  "French Indochina": "法属印度支那",
  "Ghaznavid Emirate": "加兹尼王朝",
  "Golden Horde": "金帐汗国",
  "Greek colonies": "希腊殖民地",
  "Goryeo": "高丽",
  "Grand Duchy of Moscow": "莫斯科大公国",
  "Greek city-states": "希腊城邦",
  "Gupta Empire": "笈多帝国",
  Han: "汉朝",
  "Han Empire": "汉朝",
  "Holy Roman Empire": "神圣罗马帝国",
  "Hunnic Empire": "匈人帝国",
  "Ilkhanate": "伊儿汗国",
  "Imperial Japan": "大日本帝国",
  "Inca Empire": "印加帝国",
  Jin: "晋朝",
  "Jin Empire": "金朝",
  "Japan (Warring States)": "日本战国诸侯",
  "Kara Khitai Khaganate": "西辽",
  "Kazan Khanate": "喀山汗国",
  "Kimek-Kipchak khaganate": "基马克—钦察汗国",
  "Khanate of Sibir": "西伯利亚汗国",
  "Khanate of the Golden Horde": "金帐汗国",
  "Khmer Empire": "高棉帝国",
  "Kingdom of France": "法兰西王国",
  "Kingdom of the Two Sicilies": "两西西里王国",
  "Koguryo": "高句丽",
  Korea: "朝鲜半岛政权",
  "Kwakwaka'wakw": "夸夸卡瓦夸人",
  "Kushan Empire": "贵霜帝国",
  "Kyivan Rus": "基辅罗斯",
  Liao: "辽朝",
  "Macedon and Hellenic League": "马其顿与希腊联盟",
  Magadha: "摩揭陀",
  "Mamluke Sultanate": "马穆鲁克苏丹国",
  "Manchu Empire": "清朝",
  "Maratha Confederacy": "马拉塔联盟",
  "Mauryan Empire": "孔雀王朝",
  "Ming Chinese Empire": "明朝",
  Mixtecs: "米斯特克人",
  Mogollon: "莫戈隆文化",
  "Mongol Empire": "蒙古帝国",
  Mongols: "蒙古人",
  "Mughal Empire": "莫卧儿帝国",
  "Nan Chao": "南诏",
  "Nan-Zhao": "南诏",
  "Nan-Yue": "南越",
  "Northern Liang": "北凉",
  "Northern Territory (UK)": "英属北领地",
  "Ottoman Empire": "奥斯曼帝国",
  Ouighurs: "回鹘人",
  "Papal States": "教皇国",
  Parthia: "安息",
  "Parthian Empire": "安息帝国",
  Persia: "波斯",
  "Polish–Lithuanian Commonwealth": "波兰立陶宛联邦",
  "Post-Ming Warlords": "明末军阀",
  Prussia: "普鲁士",
  "Ptolemaic Kingdom": "托勒密王国",
  "Prot-Altaic pastoralists": "原始阿尔泰语系牧民",
  "Proto-Altaic pastoralists": "原始阿尔泰语系牧民",
  "Qing Empire": "清朝",
  "Roman Empire": "罗马帝国",
  Rome: "罗马帝国",
  "Rus' Khaganate": "罗斯汗国",
  "Russian Empire": "俄罗斯帝国",
  Ruanruan: "柔然",
  "Safavid Empire": "萨法维王朝",
  "Sasanian Empire": "萨珊帝国",
  "Seleucid Kingdom": "塞琉古王国",
  Siberians: "西伯利亚人",
  "Seljuk Caliphate": "塞尔柱帝国",
  "Shogun Japan (Kamakura)": "日本镰仓幕府",
  Silla: "新罗",
  "Sixteen Kingdoms": "十六国",
  "Song Empire": "宋朝",
  "South Russia": "南俄罗斯",
  Shuar: "舒阿尔人",
  "Sui Empire": "隋朝",
  "Sultanate of Delhi": "德里苏丹国",
  "Taiwanese Tribes": "台湾原住民族",
  "Tang Empire": "唐朝",
  Tibet: "西藏",
  Tibetans: "藏族",
  "Tibetan Empire": "吐蕃帝国",
  "Toba Wei": "北魏",
  "Tokugawa Shogunate": "德川幕府",
  "Tokugawa shogunate": "德川幕府",
  "Toltec Empire": "托尔特克帝国",
  "Tsardom of Muscovy": "莫斯科沙皇国",
  "Tufan Empire": "吐蕃帝国",
  Tupis: "图皮人",
  USSR: "苏联",
  "Umayyad Caliphate": "倭马亚王朝",
  "United Kingdom of Great Britain and Ireland": "大不列颠及爱尔兰联合王国",
  "United States of America": "美国",
  Uyghurs: "回鹘人",
  Urartu: "乌拉尔图",
  "Vice Royalty of New Spain": "新西班牙总督辖区",
  "Viceroyalty of the Río de la Plata": "拉普拉塔总督辖区",
  "Visigothic Kingdom": "西哥特王国",
  "Wabanaki (Dawnland Confederacy)": "瓦巴纳基（曙光之地）联盟",
  "Western Roman Empire": "西罗马帝国",
  "Western Gokturk Khaganate": "西突厥汗国",
  Xinjiang: "新疆",
  Xiongnu: "匈奴",
  Xixia: "西夏",
  "Yamato": "大和政权",
  Yuezhi: "月氏",
  Yugoslavia: "南斯拉夫",
  "Zhangzhung Kingdom": "象雄王国",
  "Zhou states": "周代诸侯国",
  "Đại Việt": "大越",
  Göktürks: "突厥汗国",

  // Common labels in the default (1 CE) historical snapshot.
  Ainu: "阿伊努人",
  "Amazon hunter-gatherers": "亚马孙采猎者",
  "Andean hunter-gatherers": "安第斯采猎者",
  Arakan: "若开",
  "Arctic marine mammal hunters": "北极海洋哺乳动物猎人",
  "Australian aboriginal hunter-gatherers": "澳大利亚原住民采猎者",
  Axum: "阿克苏姆王国",
  "Bell-shaped burials culture": "钟形杯文化",
  Blemmyes: "布莱米人",
  Boihaenum: "波伊人之地",
  "Bosporan Kingdom": "博斯普鲁斯王国",
  "Bosporian Kingdom": "博斯普鲁斯王国",
  Bukara: "布哈拉",
  "Bukara Khanate": "布哈拉汗国",
  "Brushed Pottery culture": "刷纹陶文化",
  "Caribbean hunter-gatherers": "加勒比采猎者",
  Copena: "科佩纳文化",
  "Couture Complex": "库图尔复合体",
  Curonians: "库尔斯人",
  "Desert hunter-gatherers": "沙漠采猎者",
  Dumonii: "杜姆诺尼人",
  "Eastern Masurian culture": "东马祖里文化",
  "Finno-Ugric taiga hunter-gatherers": "芬兰—乌戈尔泰加林采猎者",
  "Fourche Maline Culture": "富什马林文化",
  "Glades Culture": "格莱兹文化",
  "Goodall Focus": "古道尔文化群",
  "Great Khanate": "大汗国（元朝）",
  Guanches: "关切人",
  Hadramaut: "哈德拉毛王国",
  Hainan: "海南",
  "Himyarite Kingdom": "希木叶尔王国",
  "Hindu kingdoms": "印度教诸王国",
  "Hopewell Culture": "霍普韦尔文化",
  Judea: "犹太",
  Kalinga: "羯陵伽",
  Khoiasan: "科伊桑人",
  "Laurel complex": "月桂复合体",
  "Marksville Culture": "马克斯维尔文化",
  Mascat: "马斯喀特",
  "Maya chiefdoms and states": "玛雅酋邦与城邦",
  Meroe: "麦罗埃王国",
  "Mill Creek Culture": "磨坊溪文化",
  Miller: "米勒文化",
  "Milograd culture": "米洛格拉德文化",
  Moche: "莫切文化",
  "Monte Albán": "蒙特阿尔班",
  "Nabatean Kingdom": "纳巴泰王国",
  Nazca: "纳斯卡文化",
  "North American Pacifi foraging, hunting and fishing peoples": "北美太平洋沿岸渔猎采集民族",
  "Odrysian Kingdom": "奥德里西亚王国",
  "Paleo-Inuit": "古因纽特人",
  "Paleo-Siberian hunter-gatherers": "古西伯利亚采猎者",
  "Pampas cultures": "潘帕斯文化",
  "Patagonian shellfish and marine mammal hunters": "巴塔哥尼亚贝类与海兽猎人",
  "Plain bison hunters": "平原野牛猎人",
  "Plain-Pottery culture": "平原陶器文化",
  "Plateau fichers and hunter gatherers": "高原渔猎采集者",
  "Point Peninsula": "点半岛文化",
  "Pomeranian culture": "波美拉尼亚文化",
  Porter: "波特文化",
  Saami: "萨米人",
  "Saka Kingdom": "塞种王国",
  "Sambian-Nothangian culture": "桑比亚—诺塔吉亚文化",
  Satavahanihara: "萨塔瓦哈纳王朝",
  "Saugeen Complex": "索金复合体",
  "Savanna hunter-gatherers": "稀树草原采猎者",
  "Shellfish gatherers": "贝类采集者",
  Simhala: "僧伽罗王国",
  "Subarctic forest hunter-gatherers": "亚北极森林采猎者",
  "Suren Kingdom": "苏伦王国",
  "Swift Creek Culture": "斯威夫特溪文化",
  "Swiss Confederation": "瑞士邦联",
  "Tasmanian hunter-gatherers": "塔斯马尼亚采猎者",
  Teotihuacán: "特奥蒂瓦坎",
  "West African cereal farmers": "西非谷物农耕者",
  "Western Masurian culture": "西马祖里文化",

  // Frequently recurring historical regions, peoples, and polities without a
  // state-form suffix in the English source data.
  Annam: "安南",
  Aceh: "亚齐",
  Alwa: "阿罗迪亚",
  Anhalt: "安哈尔特",
  Aragón: "阿拉贡",
  "Arabia (Nejd)": "内志",
  Asante: "阿散蒂",
  Ava: "阿瓦",
  Avanti: "阿般提",
  Austronesians: "南岛语族人群",
  Ayutthaya: "阿瑜陀耶",
  Bavaria: "巴伐利亚",
  Bengal: "孟加拉",
  Bantou: "班图人",
  Beothuk: "贝奥图克人",
  "Bornu-Kanem": "加涅姆—博尔努",
  Britany: "布列塔尼",
  Bunyoro: "布尼奥罗",
  "Caloosahatchee cultureure": "卡卢萨哈奇文化",
  "Cape Colony": "开普殖民地",
  Ceylon: "锡兰",
  Chavin: "查文文化",
  Chorrera: "乔雷拉文化",
  "Cochin China": "交趾支那",
  Corsica: "科西嘉",
  Dahomey: "达荷美",
  Darfur: "达尔富尔",
  "Denmark-Norway": "丹麦—挪威",
  Dorset: "多塞特文化",
  Dvaravati: "堕罗钵底",
  "East Java": "东爪哇",
  "Eastern North Amercian hunter-gatherers": "北美东部采猎者",
  Funj: "丰吉",
  Gaya: "伽倻",
  Genoa: "热那亚",
  Gujarat: "古吉拉特",
  Innu: "因纽人",
  Kandy: "康提",
  "Kashmir and Ladakh": "克什米尔与拉达克",
  Kediri: "谏义里",
  Kush: "库施",
  "Lan Na": "兰纳",
  Luba: "卢巴人",
  Lunda: "隆达",
  Lombardy: "伦巴第",
  Makkura: "马库里亚",
  Mahra: "马赫拉",
  Malacca: "马六甲",
  Malaya: "马来亚",
  "Manioc farmers": "木薯农耕者",
  Mataram: "马打兰",
  Maori: "毛利人",
  Maya: "玛雅人",
  Minang: "米南加保人",
  Milan: "米兰",
  Muscat: "马斯喀特",
  Mysore: "迈索尔",
  Naples: "那不勒斯",
  Navarre: "纳瓦拉",
  Nejd: "内志",
  "Norte Chico": "小北文明",
  Novgorod: "诺夫哥罗德",
  Orissa: "奥里萨",
  Oyo: "奥约",
  Paekche: "百济",
  Pagan: "蒲甘",
  Palas: "波罗王朝",
  Pallava: "帕拉瓦王朝",
  Pallavas: "帕拉瓦王朝",
  Paracas: "帕拉卡斯",
  "Polynesians": "波利尼西亚人",
  "Portuguese East Africa": "葡属东非",
  "Portuguese Guinea": "葡属几内亚",
  Qataban: "卡塔班",
  Ryazan: "梁赞",
  Saba: "萨巴",
  Sámi: "萨米人",
  Sardinia: "撒丁岛",
  Saxony: "萨克森",
  Scotland: "苏格兰",
  Sicily: "西西里",
  Songhai: "桑海",
  Sukhothai: "素可泰",
  Thule: "图勒文化",
  Thuringia: "图林根",
  Travancore: "特拉凡哥尔",
  Trebizond: "特拉比松",
  Tungus: "通古斯",
  Tuscany: "托斯卡纳",
  Venice: "威尼斯",
  Vijayanagara: "毗奢耶那伽罗",
  Wadai: "瓦达伊",
  Yueban: "悦般",
  Zanzibar: "桑给巴尔",

  // Additional historical polities recorded as bare place or dynastic names.
  Adal: "阿达尔",
  Ahmadnagar: "艾哈迈德讷格尔",
  Air: "阿伊尔",
  Algiers: "阿尔及尔",
  Arameans: "阿拉米人",
  Avars: "阿瓦尔人",
  Awsa: "奥萨",
  Baden: "巴登",
  Bagirmi: "巴吉尔米",
  Bidar: "比达尔",
  Bijapur: "比贾布尔",
  Bremen: "不来梅",
  Bulgars: "保加尔人",
  Burgandy: "勃艮第",
  "Chen-La": "真腊",
  Cuxhaven: "库克斯港",
  Czechoslovakia: "捷克斯洛伐克",
  Cyrenaica: "昔兰尼加",
  Finnmark: "芬马克",
  Gharra: "加拉",
  Goa: "果阿",
  "Gold Coast": "黄金海岸",
  Golkonda: "戈尔孔达",
  Granada: "格拉纳达",
  Hail: "哈伊勒",
  Hamburg: "汉堡",
  Hanover: "汉诺威",
  Hejaz: "汉志",
  Hohenzollern: "霍亨索伦",
  Holstein: "荷尔斯泰因",
  Kaarta: "卡尔塔",
  Kanem: "加涅姆",
  Karasuk: "卡拉苏克",
  Kerma: "克尔马",
  Khazars: "可萨人",
  León: "莱昂",
  "Lippe-Detmold": "利珀-代特莫尔德",
  "Lombard principalities": "伦巴第诸公国",
  Manchuria: "满洲",
  "Mesopotamia (GB)": "英属美索不达米亚",
  Mwenemutapa: "莫诺莫塔帕",
  Namazga: "纳马兹加",
  "Netherlands Indies": "荷属东印度",
  "Nogai Horde": "诺盖汗国",
  Oudh: "奥德",
  "Poland-Lithuania": "波兰—立陶宛",
  "Rio De Oro": "里奥德奥罗",
  Rozwi: "罗兹维",
  "Rupert's Land": "鲁珀特地",
  "Sardinia-Piedmont": "撒丁—皮埃蒙特",
  Scythians: "斯基泰人",
  Segu: "塞古",
  Shoa: "绍阿",
  Sotho: "索托人",
  Swedes: "瑞典人",
  Takrur: "塔克鲁尔",
  "Teutonic Knights": "条顿骑士团",
  Thrace: "色雷斯",
  Tripolitania: "的黎波里塔尼亚",
  Ur: "乌尔",
  Venetia: "威尼托",
  "Volga Bulgars": "伏尔加保加尔人",
  Waldeck: "瓦尔德克",
  "White Horde": "白帐汗国",
  Wu: "吴",
  Württemberg: "符腾堡",
  Zhoa: "周",
  Zulu: "祖鲁人",

  // Colonial administrations and protectorates in the historical snapshots.
  "Belgian Congo": "比属刚果",
  "British American colonies": "英属北美殖民地",
  "British East Africa": "英属东非",
  "British Guiana": "英属圭亚那",
  "British Protectorate": "英国保护地",
  "British Somaliland": "英属索马里兰",
  "Dutch Brazil": "荷属巴西",
  "Dutch Guiana": "荷属圭亚那",
  "Dutch Guinea": "荷属几内亚",
  "Dutch settlements": "荷兰殖民据点",
  "Dutchy of Benevento": "贝内文托公国",
  "East Germany": "东德",
  "French Cameroons": "法属喀麦隆",
  "French Equatorial Africa": "法属赤道非洲",
  "French Somaliland": "法属索马里",
  "French West Africa": "法属西非",
  "German E. Africa (Tanganyika)": "德属东非（坦噶尼喀）",
  "German South-West Africa": "德属西南非洲",
  "Germany (Soviet)": "苏占德国",
  Guiana: "圭亚那",
  "Italian Somaliland": "意属索马里",
  "Libya (IT)": "意属利比亚",
  "Mandatory Palestine (GB)": "英属巴勒斯坦托管地",
  "Northern Rhodesia": "北罗得西亚",
  "Oman (British Raj)": "英属印度治下的阿曼",
  "Portuguese Brazil": "葡属巴西",
  Rhodesia: "罗得西亚",
  "Saar Protectorate": "萨尔保护领",
  "Saharan Nomadic Tribes": "撒哈拉游牧部族",
  "Saharan pastoral nomads": "撒哈拉游牧牧民",
  "Saharan Pastoral Nomads": "撒哈拉游牧牧民",
  "Southern Rhodesia": "南罗得西亚",
  "Spanish Guinea": "西属几内亚",
  "Spanish Morocco": "西属摩洛哥",
  "Spanish Sahara": "西属撒哈拉",
  "Watassid Morocco": "瓦塔斯王朝摩洛哥",
  "West Germany": "西德",

  // Political entities and state groupings from the wider historical timeline.
  "Aghlabid Emirate": "阿格拉布王朝",
  "Almoravid dynasty": "穆拉比特王朝",
  "Andean states and chiefdoms": "安第斯诸邦与酋邦",
  "Arakan (Indian princely state)": "若开土邦",
  "Astrakhan Khanate": "阿斯特拉罕汗国",
  "Austro-Hungarian Empire": "奥匈帝国",
  "Austrian Netherlands": "奥属尼德兰",
  "Aymara kingdoms": "艾马拉诸王国",
  "Aztec Empire": "阿兹特克帝国",
  "Bahmani Kingdom": "巴赫曼尼王国",
  "Bokhara Khanate": "布哈拉汗国",
  "Borgu States": "博尔古诸国",
  "Bulgar Khanate": "保加尔汗国",
  "Burmese kingdoms": "缅甸诸王国",
  "Buyid Emirate": "白益王朝",
  "Buwayhid Emirates": "白益诸埃米尔国",
  "Caliphate of Córdoba": "科尔多瓦哈里发国",
  "central Asian khanates": "中亚诸汗国",
  "Celtic kingdoms": "凯尔特诸王国",
  "Champa City States": "占婆诸城邦",
  "Chimú Empire": "奇穆帝国",
  "city-states": "城邦",
  "Cuman Khanates": "库曼诸汗国",
  "Cuman-Kipchak confederation": "库曼—钦察联盟",
  "Croatian kingdom": "克罗地亚王国",
  "Dendi Kingdom": "登迪王国",
  "Dutch Republic": "荷兰共和国",
  "Emirate of Bin Shal'an": "伊本·沙兰埃米尔国",
  "Emirate of Sicily": "西西里埃米尔国",
  "Emirate of the White Sheep Turks": "白羊王朝",
  "Emirate of Tiflis": "第比利斯埃米尔国",
  "Empire of Alexander": "亚历山大帝国",
  "Empire of Ghana": "加纳帝国",
  "Expansionist Kingdom of Merina": "梅里纳扩张王国",
  "First Samori Empire": "萨莫里第一帝国",
  "Fulani Empire": "富拉尼帝国",
  "Georgian Kingdom": "格鲁吉亚王国",
  "German Empire": "德意志帝国",
  "Grand Duchy of Hesse": "黑森大公国",
  "Great Zimbabwe": "大津巴布韦",
  "Hafsid Caliphate": "哈夫斯王朝",
  "Helvetic Republic": "赫尔维蒂共和国",
  "Hindu Kingdoms": "印度教诸王国",
  "Hindu states": "印度教诸国",
  "Hindu kingdoms and republics": "印度教诸王国与共和国",
  "Hausa States": "豪萨诸国",
  "Huari Empire": "瓦里帝国",
  "Hurrian Kingdoms": "胡里安诸王国",
  "Icelandic Commonwealth": "冰岛自由邦",
  "Idrisid Caliphate": "伊德里斯王朝",
  "Imperial Japan (Fujiwara)": "藤原摄关时期的日本",
  "Islamic and Hindu states": "伊斯兰与印度教诸国",
  "Islamic city-states": "伊斯兰城邦",
  "Islamic states": "伊斯兰诸国",
  "Kalmar Union": "卡尔马联合",
  "Khiva Khanate": "希瓦汗国",
  "Kingdom of Antigonus": "安提柯王国",
  "Kingdom of Brazil": "巴西王国",
  "Kingdom of David and Solomon": "大卫与所罗门王国",
  "Kingdom of Gala": "加拉王国",
  "Kingdom of Georgia": "格鲁吉亚王国",
  "Kingdom of Hawaii": "夏威夷王国",
  "Kingdom of Hungary": "匈牙利王国",
  "Kō Hawaiʻi Paeʻāina (Hawaiian Kingdom)": "夏威夷王国",
  "Kingdom of Ireland": "爱尔兰王国",
  "Kingdom of Kapisa": "迦毕试王国",
  "Kingdom of Kashmir": "克什米尔王国",
  "Kingdom of Kassander": "卡山德王国",
  "Kingdom of Lysimachus": "利西马科斯王国",
  "Kingdom of Norway": "挪威王国",
  "Kingdom of Pagan": "蒲甘王国",
  "Kingdom of Sardinia": "撒丁王国",
  "Kingdom of Sind": "信德王国",
  "Kingdom of Sukhotai": "素可泰王国",
  "Kingdom of Syphax": "叙法克斯王国",
  "Kingdom of the Seven Zenden": "七泽兰共和国",
  "Kingdom of Zunbil": "尊比勒王国",
  "Kong Empire": "刚果帝国",
  "Laotian states": "老挝诸国",
  "Lopburi Kingdom": "罗布里王国",
  "Mahratta states": "马拉塔诸国",
  "Maitraka Kingdom": "迈特拉卡王国",
  "Malaysian Islamic states": "马来伊斯兰诸国",
  "Maya city-states": "玛雅城邦",
  "Maya states": "玛雅诸国",
  "Mesoamerican city-states and chiefdoms": "中部美洲城邦与酋邦",
  "Middag Kingdom": "大肚王国",
  "Ming Empire": "明朝",
  "minor Hindu & Buddhist states": "印度教与佛教小邦",
  "minor Hindu and Buddhist kingdoms": "印度教与佛教小王国",
  "minor Hindu and Buddhist states": "印度教与佛教小邦",
  "minor Hindu kingdoms": "印度教小王国",
  "minor states": "小邦",
  "minor states under Indian influence": "受印度影响的小邦",
  "Mixtec Empire": "米斯特克帝国",
  "Mon state": "孟族国家",
  "Mon States": "孟族诸国",
  "Mossi States": "莫西诸国",
  "Mysore (Indian princely state)": "迈索尔土邦",
  "Oirat Confederation": "瓦剌联盟",
  "Orange Free State": "奥兰治自由邦",
  "Ottoman Sultanate": "奥斯曼苏丹国",
  "Pallava state": "帕拉瓦王朝",
  "Pandya state": "潘地亚王朝",
  "Principality of Galicia-Volhynia": "加利西亚—沃里尼亚公国",
  "Principality of Kyiv": "基辅公国",
  "Principality of Novgorod": "诺夫哥罗德公国",
  "Principality of Polotsk": "波洛茨克公国",
  "Principality of Vladimir-Suzdal": "弗拉基米尔—苏兹达尔公国",
  "Principality of Wallachia": "瓦拉几亚公国",
  "Pyu state": "骠国",
  "Quazaq Khanate": "哈萨克汗国",
  "Rajput Clans and Small States": "拉其普特氏族与小邦",
  "Rajput kingdoms": "拉其普特诸王国",
  "Rajput Kingdoms": "拉其普特诸王国",
  "Rashtrakuta state": "拉什特拉库塔王朝",
  "Rattanakosin Kingdom": "拉达那哥欣王国",
  "Republic of Kraków": "克拉科夫共和国",
  "Republic of the Seven Zenden": "七泽兰共和国",
  "Rift Valley States": "裂谷诸国",
  "Roman Republic": "罗马共和国",
  "Samanid Empire": "萨曼王朝",
  "Second Samori Empire": "萨莫里第二帝国",
  "Seljuk Empire": "塞尔柱帝国",
  "Shan states": "掸邦诸国",
  "Sinhalese kingdom": "僧伽罗王国",
  "Sinhalese kingdoms": "僧伽罗诸王国",
  "Sikkim (Indian princely state)": "锡金土邦",
  "Sokoto Caliphate": "索科托哈里发国",
  "Soomra Emirate": "苏姆拉王朝",
  "Srivijaya Empire": "三佛齐（室利佛逝）",
  "state societies and Aramaean kingdoms": "国家社会与阿拉米诸王国",
  "Sultanate of Damagaram": "达马加拉姆苏丹国",
  "Sultanate of Utetera": "乌特泰拉苏丹国",
  "Thai Kingdoms": "泰人诸王国",
  "Tiahuanaco Empire": "蒂亚瓦纳科帝国",
  "Timurid Empire": "帖木儿帝国",
  "Timurid Emirates": "帖木儿诸埃米尔国",
  "Trucial Oman": "特鲁西尔阿曼",
  Turan: "突兰",
  "Tukular Caliphate": "图库洛尔哈里发国",
  "Tuʻi Tonga Empire": "图伊汤加帝国",
  "Union of South Africa": "南非联邦",
  "Vice Royalty of Peru": "秘鲁总督辖区",
  "Vice-Royalty of Brazil": "巴西总督辖区",
  "Vice-Royalty of New Granada": "新格拉纳达总督辖区",
  "Vice-Royalty of New Spain": "新西班牙总督辖区",
  "Vice-Royalty of Peru": "秘鲁总督辖区",
  "Viceroyalty of Brazil": "巴西总督辖区",
  "Wadai Empire": "瓦达伊帝国",
  "Wassoulou Empire": "瓦苏卢帝国",
  "Wattasid Caliphate": "瓦塔斯王朝",
  "Zapotec Empire": "萨波特克帝国",
  "Zayyanid Caliphate": "扎扬王朝",
  "Zhow states": "周代诸侯国",

  // Remaining state, colony, and administration labels from the later historical snapshots.
  Abyssinia: "埃塞俄比亚",
  "Acadian Peninsula (UK)": "英属阿卡迪亚半岛",
  Accra: "阿克拉",
  Ambur: "安布尔",
  "Anglo-Egyption Sudan": "英埃苏丹",
  Assam: "阿萨姆",
  Bahawalpur: "巴哈瓦尔布尔",
  Barotse: "巴罗策",
  Basutoland: "巴苏陀兰",
  "Bosnia-Herzegovina": "波斯尼亚和黑塞哥维那",
  Brunswick: "不伦瑞克",
  Buganda: "布干达",
  Bundelkhand: "本德尔坎德",
  Calabar: "卡拉巴尔",
  Carnatic: "卡纳提克",
  Circars: "北萨卡尔",
  Cochin: "科钦",
  Cotonou: "科托努",
  "Cyraneica (UK Lybia)": "英属昔兰尼加",
  Danzig: "但泽",
  "Delagoa Bay": "德拉瓜湾",
  "Dominion of Newfoundland": "纽芬兰自治领",
  "East Prussia": "东普鲁士",
  "Electoral Hesse": "黑森选侯国",
  Fante: "芳蒂",
  "Far Eastern SSR": "远东共和国",
  "Fezzan (Frech Lybia)": "法属费赞",
  "Futa Jalon": "富塔贾隆",
  "Futa Toro": "富塔托罗",
  "Gilbert and Elice Islands": "吉尔伯特和埃利斯群岛",
  Gooty: "古蒂",
  "Griqualand West": "西格里夸兰",
  "Harer (Egypt)": "埃及属哈勒尔",
  Ibadan: "伊巴丹",
  Imbangala: "因班加拉",
  Imerina: "伊梅里纳",
  Kamerun: "喀麦隆",
  Kanara: "卡纳拉",
  "Kanem-Bornu": "加涅姆-博尔努",
  Kazembe: "卡赞贝",
  "Kingfom of Italy": "意大利王国",
  Kong: "孔格",
  "Kongldom of Hawaii": "夏威夷王国",
  Kuba: "库巴王国",
  Lagos: "拉各斯",
  Lozi: "洛兹",
  Lübeck: "吕贝克",
  Lucca: "卢卡",
  Luisiana: "路易斯安那",
  Madras: "马德拉斯",
  Malabar: "马拉巴尔",
  "Mecklenburg-Schwerin": "梅克伦堡-什未林",
  "Mecklenburg-Strelitz": "梅克伦堡-施特雷利茨",
  "Mirambo Unyanyembe Ukimbu": "米兰博—乌尼亚涅姆贝—乌金布",
  Modena: "摩德纳",
  "Muscat and Oman": "马斯喀特和阿曼",
  Nassau: "拿骚",
  Natal: "纳塔尔",
  "New Hebrides": "新赫布里底",
  "New South Wales": "新南威尔士",
  "New South Wales (UK)": "英属新南威尔士",
  "Nizam's Dominions": "海得拉巴尼扎姆领地",
  Nkore: "恩科雷",
  Nyasaland: "尼亚萨兰",
  Oldenburg: "奥尔登堡",
  Opobo: "奥波博",
  Palatinate: "普法尔茨",
  Papou: "巴布亚",
  Parma: "帕尔马",
  Quebec: "魁北克",
  "Queensland (UK)": "英属昆士兰",
  "Rabih az-Zubayr": "拉比赫·祖拜尔",
  Saipan: "塞班",
  "Sakhalin (RU)": "俄属库页岛",
  "Schaumburg-Lippe": "绍姆堡-利珀",
  Schleswig: "石勒苏益格",
  Siam: "暹罗",
  Sindh: "信德",
  "Southern Cameroon": "南喀麦隆",
  "Sultinate of Zanzibar": "桑给巴尔苏丹国",
  Swabia: "施瓦本",
  "Sweden–Norway": "瑞典-挪威联合王国",
  Togoland: "多哥兰",
  Tonkin: "东京",
  Transvaal: "德兰士瓦",
  "Tripolitana (UK Lybia)": "英属的黎波里塔尼亚",
  Tunis: "突尼斯",
  "United Provinces of La Plata": "拉普拉塔联合省",
  "Victoria (UK)": "英属维多利亚",
  "Walbis Bay": "鲸湾",
  "Western Australia (UK)": "英属西澳大利亚",
  Wetzlar: "韦茨拉尔",
  "White Russia": "白俄罗斯",
  Zululand: "祖鲁兰",
};

const colonialOwners: Record<string, string> = {
  Austria: "奥属",
  Belgium: "比属",
  Danemark: "丹属",
  Dutch: "荷属",
  FR: "法属",
  France: "法属",
  GB: "英属",
  Italy: "意属",
  Netherlands: "荷属",
  Portugal: "葡属",
  Spain: "西属",
  UK: "英属",
  USA: "美占",
  USSR: "苏占",
};

function buildRegionNames() {
  if (typeof Intl.DisplayNames !== "function") return new Map<string, string>();
  const english = new Intl.DisplayNames(["en"], { type: "region" });
  const chinese = new Intl.DisplayNames(["zh-CN"], { type: "region" });
  const names = new Map<string, string>();
  for (let first = 65; first <= 90; first += 1) {
    for (let second = 65; second <= 90; second += 1) {
      const code = String.fromCharCode(first, second);
      const englishName = english.of(code);
      const chineseName = chinese.of(code);
      if (englishName && chineseName && englishName !== code && chineseName !== code) names.set(englishName, chineseName);
    }
  }
  return names;
}

const regionNames = buildRegionNames();
const containsChinese = /[\u3400-\u9fff]/u;

function normalizedTerritoryKey(name: string) {
  return name
    .normalize("NFKD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[‘’`´]/gu, "'")
    .replace(/[-–—]/gu, "-")
    .replace(/\s+/gu, " ")
    .toLowerCase();
}

function buildNormalizedNames(entries: Iterable<[string, string]>) {
  const names = new Map<string, string>();
  for (const [name, chineseName] of entries) {
    const key = normalizedTerritoryKey(name);
    if (!names.has(key)) names.set(key, chineseName);
  }
  return names;
}

const normalizedChineseOverrides = buildNormalizedNames(Object.entries(chineseOverrides));
const normalizedRegionNames = buildNormalizedNames(regionNames.entries());

function knownChineseTerritoryName(name: string) {
  return chineseOverrides[name]
    ?? regionNames.get(name)
    ?? normalizedChineseOverrides.get(normalizedTerritoryKey(name))
    ?? normalizedRegionNames.get(normalizedTerritoryKey(name));
}

export function chineseTerritoryName(name: string) {
  const trimmed = name.trim();
  if (!trimmed || trimmed === "?") return null;
  if (containsChinese.test(trimmed)) return trimmed;
  const direct = knownChineseTerritoryName(trimmed);
  if (direct) return direct;

  const colonial = /^(.*?) \((.*?)\)$/.exec(trimmed);
  if (colonial) {
    const base = knownChineseTerritoryName(colonial[1]!);
    const owner = colonialOwners[colonial[2]!];
    if (base && owner) return `${owner}${base}`;
  }
  return null;
}

export function localizedTerritoryName(entity: PoliticalEntity, language: "en" | "zh") {
  const englishName = entity.nameEn ?? entity.name;
  if (language === "en") return englishName;
  return chineseTerritoryName(entity.name) ?? chineseTerritoryName(englishName);
}
